---
- name: Restart zot
  ansible.builtin.systemd:
    name: zot
    state: restarted
    daemon_reload: true

- name: Reload registry caddy
  ansible.builtin.systemd:
    name: "{{ zot_registry_caddy_service_name }}"
    state: restarted
    daemon_reload: true
