import React from "react"
import { renderToString } from "react-dom/server"
import { describe, expect, it } from "vitest"
import HomePage from "./page"

describe("RootPage", () => {
  it("renders the complete landing page at the canonical root entry point", () => {
    const html = renderToString(React.createElement(HomePage))

    expect(html).toContain("Productive ai agents for your entire team.")
    expect(html).toContain("With no monthly subscriptions")
    expect(html).toContain(
      "Stop wasting tokens - pick the right model for the right job"
    )
    expect(html).toContain("DeepSeek V4 Flash")
    expect(html).toContain("Claude Sonnet 5")
    expect(html).toContain("GPT-5.3 Codex")
    expect(html).toContain("KAT Coder Air V2.5")
    expect(html).toContain("Search 18 available models")
    expect(html).toContain("Claude Opus 4.7")
    expect(html).toContain("Kimi K2.7 Code")
    expect(html).toContain("Xiaomi MiMo V2.5 Pro")
    expect(html).toContain("StepFun Step 3.7 Flash")
    expect(html).toContain("InclusionAI Ling 2.6 1T")
    expect(html).toContain("NVIDIA Nemotron 3 Nano")
    expect(html).toContain("Five agents. Five right-sized models.")
    expect(html).toContain("Support agent")
    expect(html).toContain("Operations agent")
    expect(html).not.toContain("Document agent")
    expect(html).not.toContain("Workflow agent")
    expect(html).not.toContain("Data agent")
    expect(html).not.toContain("Infrastructure agent")
    expect(html).toContain("Model prices pass through with 0% markup.")
    expect(html).not.toContain("Describe it. Hivy builds it.")
    expect(html).not.toContain("Watch every run, end to end.")
    expect(html).not.toContain("Everything your agents need, in one workspace.")
    expect(html).not.toContain("Build, run, and watch every agent.")
    expect(html).toContain("Turn a Slack message into finished work.")
    expect(html).toContain("Let the next signal start the right agent.")
    expect(html).toContain(
      "Give every agent what the job needs. Nothing outside it."
    )
    expect(html).toContain('href="/tag"')
    expect(html).toContain('href="/automations"')
    expect(html).toContain('href="/access-control"')
    expect(html).toContain("Explore Hivy Tag")
    expect(html).toContain("Explore automations")
    expect(html).toContain("Explore access control")
    expect(html).toContain("connections-light-mode.png")
    expect(html).toContain("connections-dark-mode.png")
    expect(html).toContain("knowledge-base-light-mode.png")
    expect(html).toContain("knowledge-base-dark-mode.png")
    expect(html).toContain(
      "Hivy connection catalog with databases and company integrations"
    )
    expect(html).toContain(
      "Hivy knowledge source setup with GitHub, Notion, Slack, Linear, and website sources"
    )
    expect(html).toContain("Build your first agent today.")
    expect(html).toContain(
      "Main Hivy workspace product screenshot, placeholder"
    )
    expect(html).not.toContain("Trusted by technical teams at")
    expect(html).not.toContain("Aster placeholder logo")
    expect(html).not.toContain("Current placeholder logo")
    expect(html).not.toContain("Global work done by Hivy")
    expect(html).not.toContain(">Solutions<")
    expect(html).toContain("Knowledge base")
    expect(html).toContain("Agents")
    expect(html).toContain("Drive")
    expect(html).toContain("Automations")
    expect(html).toContain("Sheets")
    expect(html).toContain("Access control")
    expect(html).toContain('href="/knowledge"')
    expect(html).toContain('href="/agents"')
    expect(html).toContain('href="/drive"')
    expect(html).toContain('href="/automations"')
    expect(html).toContain('href="/sheets"')
    expect(html).toContain('href="/access-control"')
    expect(html).toContain("Docs")
    expect(html).toContain("Blog")
    expect(html).toContain("Changelog")
    expect(html).toContain("Models")
    expect(html).toContain("0.1k")
    expect(html).toContain("Watch a 2min demo")
    expect(html).toContain('aria-label="github"')
    expect(html).toContain("Start for free")
    expect(html).not.toContain("Sign up")
    expect(html).not.toContain("Request a demo")
    expect(html).not.toContain("Contact sales")
    expect(html).toContain('href="/auth/signup"')
    expect(html).toContain("marketing-link-scope")
    expect(html).toContain("marketing-menu-link")
  })
})
