apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: observability-grafana-admin
    envs:
      - grafana-admin.env
    type: Opaque
  - name: observability-telemetry-ingest
    envs:
      - telemetry-ingest.env
    type: Opaque
generatorOptions:
  disableNameSuffixHash: true
