package handler

import (
	"archive/zip"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/usehivy/hivy/internal/logging"
)

// defaultAppsTemplateDir is the in-repo app template, resolved relative to
// the server working directory like the other global assets
// (NewAutomationCatalogHandler uses "global/triggers" the same way).
const defaultAppsTemplateDir = "global/apps/template"

// The zip ships app scaffolding, not this repo's CI surface: build outputs
// and dependency caches are rebuilt in the sandbox, and the template's own
// tests are platform machinery builder agents must never see — they verify
// their app by driving the preview, not by running our suite.

// appsTemplateZipExcludedDirs are directory names pruned from the archive
// wherever they appear.
var appsTemplateZipExcludedDirs = map[string]bool{
	"node_modules": true, // dependency cache — rebuilt by `make deps`
	"dist":         true, // build artifacts — rebuilt by `make all`
	"public":       true, // Vite build output — regenerated by `make web`
	".git":         true, // repo metadata
	"testdata":     true, // Go test fixtures
	"fixtures":     true, // test fixtures
	"__tests__":    true, // JS/TS test convention
}

// appsTemplateZipExcludedFiles are glob patterns, matched with path.Match
// against each file's base name, for files stripped wherever they appear.
var appsTemplateZipExcludedFiles = []string{
	"*_test.go",       // Go tests (colocated with hivycore/api sources)
	"*.test.*",        // Vitest colocated tests (web/src/**/*.test.ts(x))
	"vitest.config.*", // Vitest config — meaningless without the tests
	".git*",           // .gitignore, .gitattributes, …
}

// appsTemplateZipExcludesFile reports whether a file base name matches the
// exclusion table above.
func appsTemplateZipExcludesFile(name string) bool {
	for _, pattern := range appsTemplateZipExcludedFiles {
		if matched, err := path.Match(pattern, name); err == nil && matched {
			return true
		}
	}
	return false
}

// WithAppsTemplateDir overrides the app template directory (tests).
func (h *UploadsHandler) WithAppsTemplateDir(dir string) *UploadsHandler {
	h.appsTemplateDir = dir
	return h
}

func (h *UploadsHandler) resolvedAppsTemplateDir() string {
	if strings.TrimSpace(h.appsTemplateDir) != "" {
		return h.appsTemplateDir
	}
	return defaultAppsTemplateDir
}

// StreamAppsTemplateZip streams a zip of the app template, built at request
// time, to a builder agent. Auth is the existing sandbox runtime-secret
// bearer (authAgent) — builders derive this URL from HIVY_DRIVE_UPLOAD_URL by
// replacing the /drive suffix with /apps-template.zip.
//
//	GET /internal/agents/{agentID}/sandboxes/{sandboxID}/apps-template.zip
func (h *UploadsHandler) StreamAppsTemplateZip(w http.ResponseWriter, r *http.Request) {
	agent, _, ok := h.authAgent(w, r)
	if !ok {
		return
	}

	root := h.resolvedAppsTemplateDir()
	if info, err := os.Stat(root); err != nil || !info.IsDir() {
		writeJSON(w, http.StatusServiceUnavailable, map[string]string{"error": "app template is not available"})
		return
	}

	w.Header().Set("Content-Type", "application/zip")
	w.Header().Set("Content-Disposition", `attachment; filename="apps-template.zip"`)
	w.WriteHeader(http.StatusOK)

	zw := zip.NewWriter(w)
	err := filepath.WalkDir(root, func(walkPath string, entry fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		if entry.IsDir() {
			if walkPath != root && appsTemplateZipExcludedDirs[entry.Name()] {
				return filepath.SkipDir
			}
			return nil
		}
		if !entry.Type().IsRegular() {
			return nil // no symlinks or devices in the archive
		}
		if appsTemplateZipExcludesFile(entry.Name()) {
			return nil
		}
		rel, err := filepath.Rel(root, walkPath)
		if err != nil {
			return err
		}
		info, err := entry.Info()
		if err != nil {
			return err
		}
		header, err := zip.FileInfoHeader(info)
		if err != nil {
			return err
		}
		header.Name = filepath.ToSlash(rel)
		header.Method = zip.Deflate
		dst, err := zw.CreateHeader(header)
		if err != nil {
			return err
		}
		src, err := os.Open(walkPath)
		if err != nil {
			return err
		}
		defer src.Close()
		_, err = io.Copy(dst, src)
		return err
	})
	if err != nil {
		// Headers are already flushed — closing the writer mid-archive leaves
		// the client with a truncated zip, which is the correct failure signal.
		logging.FromContext(r.Context()).ErrorContext(r.Context(), "apps template zip stream failed",
			"agent_id", agent.ID, "error", err)
	}
	if err := zw.Close(); err != nil {
		logging.FromContext(r.Context()).ErrorContext(r.Context(), "apps template zip close failed",
			"agent_id", agent.ID, "error", err)
	}
}
