package handler

import (
	"context"
	"net/http"
	"time"

	"github.com/google/uuid"

	"github.com/usehivy/hivy/internal/model"
)

const (
	sessionNameUpdatePollInterval = time.Second
	sessionNameUpdateKeepalive    = 15 * time.Second
	sessionNameUpdateTimeout      = 35 * time.Second
)

type sessionNameUpdateResponse struct {
	Session sessionResponse `json:"session"`
}

func (h *SessionHandler) StreamNameUpdates(w http.ResponseWriter, r *http.Request) {
	session, _, ok := h.authorizeSession(w, r, false)
	if !ok {
		return
	}

	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache, no-transform")
	w.Header().Set("Connection", "keep-alive")
	w.Header().Set("X-Accel-Buffering", "no")
	rc := http.NewResponseController(w)
	_ = rc.Flush()

	if done := h.emitGeneratedSessionName(r.Context(), rc, w, session.ID); done {
		return
	}

	ticker := time.NewTicker(sessionNameUpdatePollInterval)
	defer ticker.Stop()
	keepalive := time.NewTicker(sessionNameUpdateKeepalive)
	defer keepalive.Stop()
	timeout := time.NewTimer(sessionNameUpdateTimeout)
	defer timeout.Stop()

	for {
		select {
		case <-r.Context().Done():
			return
		case <-timeout.C:
			_ = writeSessionSSE(rc, w, "session.name.timeout", "", map[string]any{
				"session_id": session.ID.String(),
			})
			return
		case <-keepalive.C:
			if err := writeSessionSSE(rc, w, "session.name.keepalive", "", map[string]any{
				"session_id": session.ID.String(),
			}); err != nil {
				return
			}
		case <-ticker.C:
			if done := h.emitGeneratedSessionName(r.Context(), rc, w, session.ID); done {
				return
			}
		}
	}
}

func (h *SessionHandler) emitGeneratedSessionName(ctx context.Context, rc *http.ResponseController, w http.ResponseWriter, sessionID uuid.UUID) bool {
	session, ready, err := h.loadGeneratedSessionName(ctx, sessionID)
	if err != nil {
		_ = writeSessionSSE(rc, w, "session.name.error", "", map[string]any{
			"session_id": sessionID.String(),
			"error":      "failed to load session name",
		})
		return true
	}
	if !ready {
		return false
	}
	stats := h.statsForSessions(ctx, []uuid.UUID{session.ID})[session.ID]
	_ = writeSessionSSE(rc, w, "session.name", "", sessionNameUpdateResponse{
		Session: sessionToResponse(session, stats.ParticipantCount, stats.EventCount, stats.LastEvent),
	})
	return true
}

func (h *SessionHandler) loadGeneratedSessionName(ctx context.Context, sessionID uuid.UUID) (model.Session, bool, error) {
	var session model.Session
	if err := h.db.WithContext(ctx).First(&session, "id = ?", sessionID).Error; err != nil {
		return model.Session{}, false, err
	}
	return session, session.SessionNameAutoGeneratedAt != nil, nil
}
