import type { IconSvgElement } from "@hugeicons/react"
import type { ComponentType, SVGProps } from "react"
import {
  Activity,
  AiBrowserIcon,
  AlertTriangle,
  Archive,
  ArrowDownAZ,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpAZ,
  ArrowUpDown,
  ArrowUpRight,
  BanIcon,
  Bot,
  Braces,
  Brain,
  Bug,
  Calendar,
  Camera,
  ChartSpline,
  CheckIcon,
  CheckmarkCircle02Icon,
  CheckmarkSquare01Icon,
  Tick02Icon,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleChevronDownIcon,
  CirclePlus,
  CircleUser,
  Clock,
  ClockAlertIcon,
  CodeXml,
  Coins,
  Columns2,
  Columns3,
  ComputerTerminal01Icon,
  Cookie,
  Copy,
  CornerDownLeft,
  Cpu,
  CreditCard,
  Database,
  Download,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  FileDiffIcon,
  FileDown,
  FilePlus,
  FileSearch,
  FileText,
  FileUp,
  Focus,
  Folder,
  FolderOpen,
  FolderSearch,
  FolderX,
  GaugeIcon,
  GitBranch,
  GitFork,
  Globe,
  Hammer,
  Hash,
  Heading,
  Headset,
  Highlighter,
  History,
  Image,
  ImageOff,
  Info,
  KeyRound,
  Keyboard,
  Layout,
  LayoutGrid,
  LayoutIcon,
  Link,
  ListChecks,
  ListFilter,
  ListOrdered,
  ListTree,
  LoaderCircle,
  Loading03Icon,
  LogOut,
  Mail,
  Maximize2,
  MessageCircle,
  MessageQuestionIcon,
  MessageSquare,
  MessageSquarePlus,
  MessagesSquare,
  Mic,
  Minimize2,
  Monitor,
  Moon,
  Mouse,
  MousePointer2,
  MousePointerClick,
  Move,
  MoveVertical,
  Network,
  Package,
  PackageOpen,
  Palette,
  PanelLeft,
  PanelLeftOpen,
  PanelRight,
  PanelRightClose,
  PanelTop,
  Paperclip,
  PenLine,
  Pencil,
  Phone,
  Play,
  Plug,
  PlugZap,
  Plus,
  Presentation,
  Radar,
  RefreshCw,
  RotateCcw,
  RotateCw,
  Route,
  Rows3,
  Save,
  Scan,
  ScanSearch,
  Scroll,
  Search,
  Select01Icon,
  Send,
  Settings,
  Share,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Square,
  SquareArrowRight01Icon,
  SquarePen,
  Sun,
  Table,
  Tablet,
  Telescope,
  Terminal,
  TestTube,
  Text,
  TextCursorInput,
  TextSearch,
  ThumbsDown,
  ThumbsUp,
  ToyBrickIcon,
  Trash2,
  Type,
  Undo2,
  Unlink,
  Upload,
  UserGroupIcon,
  UserPlus,
  Users,
  Video,
  Workflow,
  X,
} from "@hugeicons/core-free-icons"
import { createElement } from "react"
import ThesvgChrome from "@thesvg/react/chrome"
import ThesvgGithub from "@thesvg/react/github"
import ThesvgGoogle from "@thesvg/react/google"
import ThesvgLinear from "@thesvg/react/linear"
import ThesvgMongodb from "@thesvg/react/mongodb"
import ThesvgMysql from "@thesvg/react/mysql"
import ThesvgNotion from "@thesvg/react/notion"
import ThesvgPlaywright from "@thesvg/react/playwright"
import ThesvgPostgresql from "@thesvg/react/postgresql"
import ThesvgRailway from "@thesvg/react/railway"
import ThesvgRedis from "@thesvg/react/redis"
import ThesvgSlack from "@thesvg/react/slack"
import ThesvgVercel from "@thesvg/react/vercel"
import ThesvgX from "@thesvg/react/x"

export type RegisteredIcon = IconSvgElement | ComponentType<SVGProps<SVGSVGElement>>

/**
 * Brand marks come from @thesvg/react. We prefer the "mono" variant so brands
 * tint via currentColor like every other icon; components without a mono
 * variant (e.g. slack, chrome) ignore it and render their full-color default
 * mark. The cast is needed because each generated component narrows `variant`
 * to its own union, which may not include "mono".
 */
function brand(
  Component: ComponentType<SVGProps<SVGSVGElement>>
): ComponentType<SVGProps<SVGSVGElement>> {
  const Branded = Component as ComponentType<
    SVGProps<SVGSVGElement> & { variant?: string }
  >
  function BrandIcon(props: SVGProps<SVGSVGElement>) {
    return createElement(Branded, { variant: "mono", ...props })
  }
  return BrandIcon
}

/**
 * Central icon registry: clean kebab-case names -> statically imported icons.
 *
 * Values are either a hugeicons `IconSvgElement` (rendered via `<HugeiconsIcon>`)
 * or a custom React SVG component (hand-authored brand logos in ./brand).
 */
export const iconRegistry: Record<string, RegisteredIcon> = {
  // ---- Lucide-alias exports from @hugeicons/core-free-icons ----
  check: CheckIcon,
  plus: Plus,
  x: X,
  hash: Hash,
  hammer: Hammer,
  "app-window": AiBrowserIcon,
  "arrow-left": ArrowLeft,
  "chevron-down": ChevronDown,
  bot: Bot,
  pencil: Pencil,
  "chevron-right": ChevronRight,
  "circle-alert": CircleAlert,
  "trash-2": Trash2,
  search: Search,
  "refresh-cw": RefreshCw,
  plug: Plug,
  "arrow-right": ArrowRight,
  square: Square,
  "message-square": MessageSquare,
  archive: Archive,
  table: Table,
  settings: Settings,
  "loader-circle": LoaderCircle,
  "text-cursor-input": TextCursorInput,
  "file-up": FileUp,
  ellipsis: Ellipsis,
  download: Download,
  workflow: Workflow,
  "user-plus": UserPlus,
  "mouse-pointer-click": MousePointerClick,
  monitor: Monitor,
  mic: Mic,
  mail: Mail,
  "list-checks": ListChecks,
  "layout-grid": LayoutGrid,
  "key-round": KeyRound,
  "file-text": FileText,
  "external-link": ExternalLink,
  copy: Copy,
  "columns-3": Columns3,
  clock: Clock,
  camera: Camera,
  braces: Braces,
  upload: Upload,
  unlink: Unlink,
  sun: Sun,
  share: Share,
  "scan-search": ScanSearch,
  save: Save,
  "rows-3": Rows3,
  "rotate-cw": RotateCw,
  play: Play,
  paperclip: Paperclip,
  "panel-right-close": PanelRightClose,
  "mouse-pointer-2": MousePointer2,
  "messages-square": MessagesSquare,
  "message-square-plus": MessageSquarePlus,
  "list-filter": ListFilter,
  link: Link,
  keyboard: Keyboard,
  info: Info,
  image: Image,
  globe: Globe,
  "git-fork": GitFork,
  "git-branch": GitBranch,
  "folder-search": FolderSearch,
  folder: Folder,
  focus: Focus,
  "eye-off": EyeOff,
  "code-xml": CodeXml,
  "circle-user": CircleUser,
  "circle-check": CheckmarkCircle02Icon,
  "tick-02": Tick02Icon,
  "chevron-up": ChevronUp,
  "arrow-up": ArrowUp,
  video: Video,
  users: Users,
  "undo-2": Undo2,
  type: Type,
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,
  "text-search": TextSearch,
  text: Text,
  terminal: Terminal,
  "test-tube": TestTube,
  telescope: Telescope,
  tablet: Tablet,
  "square-pen": SquarePen,
  sparkles: Sparkles,
  smartphone: Smartphone,
  "shield-check": ShieldCheck,
  send: Send,
  scroll: Scroll,
  scan: Scan,
  route: Route,
  "rotate-ccw": RotateCcw,
  presentation: Presentation,
  "plug-zap": PlugZap,
  phone: Phone,
  "pen-line": PenLine,
  "panel-top": PanelTop,
  "panel-right": PanelRight,
  "panel-left-open": PanelLeftOpen,
  "panel-left": PanelLeft,
  palette: Palette,
  "package-open": PackageOpen,
  package: Package,
  network: Network,
  "move-vertical": MoveVertical,
  move: Move,
  mouse: Mouse,
  moon: Moon,
  "minimize-2": Minimize2,
  "message-circle": MessageCircle,
  "maximize-2": Maximize2,
  "log-out": LogOut,
  "list-tree": ListTree,
  "list-ordered": ListOrdered,
  layout: Layout,
  "image-off": ImageOff,
  history: History,
  highlighter: Highlighter,
  headset: Headset,
  heading: Heading,
  "folder-x": FolderX,
  "folder-open": FolderOpen,
  "file-search": FileSearch,
  "file-plus": FilePlus,
  "file-down": FileDown,
  eye: Eye,
  "ellipsis-vertical": EllipsisVertical,
  database: Database,
  "credit-card": CreditCard,
  "corner-down-left": CornerDownLeft,
  cookie: Cookie,
  "columns-2": Columns2,
  coins: Coins,
  "circle-plus": CirclePlus,
  circle: Circle,
  "chevron-left": ChevronLeft,
  "check-circle": CheckmarkCircle02Icon,
  "chart-spline": ChartSpline,
  calendar: Calendar,
  bug: Bug,
  brain: Brain,
  "arrow-up-right": ArrowUpRight,
  "arrow-up-down": ArrowUpDown,
  "arrow-up-a-z": ArrowUpAZ,
  "arrow-down-a-z": ArrowDownAZ,
  activity: Activity,
  cpu: Cpu,
  radar: Radar,

  // ---- Manual mappings (lucide names without a matching bare alias) ----
  "triangle-alert": AlertTriangle,
  "users-round": UserGroupIcon,
  "panels-top-left": LayoutIcon,
  "loader-2": Loading03Icon,
  "square-terminal": ComputerTerminal01Icon,
  "square-chevron-right": SquareArrowRight01Icon,
  "square-check": CheckmarkSquare01Icon,
  "panel-top-open": PanelTop,
  "message-circle-question": MessageQuestionIcon,
  "circle-slash": BanIcon,
  "check-circle-2": CheckmarkCircle02Icon,
  "box-select": Select01Icon,
  "file-diff": FileDiffIcon,
  "clock-alert": ClockAlertIcon,
  gauge: GaugeIcon,
  "toy-brick": ToyBrickIcon,
  "circle-chevron-down": CircleChevronDownIcon,

  // ---- Brand icons (@thesvg/react, mono variant where available) ----
  github: brand(ThesvgGithub),
  slack: brand(ThesvgSlack),
  notion: brand(ThesvgNotion),
  chrome: brand(ThesvgChrome),
  google: brand(ThesvgGoogle),
  "twitter-x": brand(ThesvgX),
  linear: brand(ThesvgLinear),
  playwright: brand(ThesvgPlaywright),
  postgresql: brand(ThesvgPostgresql),
  railway: brand(ThesvgRailway),
  redis: brand(ThesvgRedis),
  vercel: brand(ThesvgVercel),
  mongodb: brand(ThesvgMongodb),
  mysql: brand(ThesvgMysql),
}
