all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519

  children:
    runners:
      hosts:
        runner1:
          ansible_host: 203.0.113.10
          runner_name: runner-1
          runner_public_url: http://203.0.113.10:8081
