all:
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/usehivy

  children:
    preview_proxy:
      hosts:
        caddy:
          ansible_host: 46.62.169.26
          preview_proxy_private_ip: 10.80.0.2

    runners:
      hosts:
        runner0:
          ansible_host: 135.181.238.109
          runner_name: 0-runner-sandboxes-hivy-com
          runner_public_url: http://135.181.238.109:8081
