apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - ../config/env/observability
  - routes.yaml
  - network-policy.yaml

configMapGenerator:
  - name: hivy-grafana-dashboards
    files:
      - dashboards/hivy-overview.json
      - dashboards/hivy-service-details.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
