package migrations_test

import (
	"net/url"
	"strings"
	"testing"

	"github.com/google/uuid"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"

	"github.com/usehivy/hivy/internal/migrations"
	"github.com/usehivy/hivy/internal/testdb"
)

func TestCreditPurchasesMigrationUpgradesVersionOneProductionSchema(t *testing.T) {
	baseURL := testdb.DatabaseURL("DATABASE_URL", "HIVY_DATABASE_URL", "TEST_DATABASE_URL")
	databaseName := "hivy_migration_" + strings.ReplaceAll(uuid.NewString(), "-", "")
	maintenanceURL, databaseURL := migrationTestURLs(t, baseURL, databaseName)

	maintenance, err := gorm.Open(postgres.Open(maintenanceURL), &gorm.Config{})
	if err != nil {
		t.Fatalf("connect maintenance database: %v", err)
	}
	maintenanceSQL, err := maintenance.DB()
	if err != nil {
		t.Fatalf("maintenance database handle: %v", err)
	}
	if err := maintenance.Exec(`CREATE DATABASE ` + databaseName).Error; err != nil {
		_ = maintenanceSQL.Close()
		t.Fatalf("create migration test database: %v", err)
	}

	database, err := gorm.Open(postgres.Open(databaseURL), &gorm.Config{})
	if err != nil {
		_ = maintenance.Exec(`DROP DATABASE IF EXISTS ` + databaseName).Error
		_ = maintenanceSQL.Close()
		t.Fatalf("connect migration test database: %v", err)
	}
	databaseSQL, err := database.DB()
	if err != nil {
		t.Fatalf("migration database handle: %v", err)
	}
	t.Cleanup(func() {
		_ = databaseSQL.Close()
		_ = maintenance.Exec(`DROP DATABASE IF EXISTS ` + databaseName).Error
		_ = maintenanceSQL.Close()
	})

	for _, statement := range []string{
		`CREATE TABLE public.orgs (id uuid PRIMARY KEY, plan_slug character varying(64) DEFAULT 'free' NOT NULL)`,
		`CREATE TABLE public.users (id uuid PRIMARY KEY)`,
		`CREATE TABLE public.goose_db_version (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version_id bigint NOT NULL, is_applied boolean NOT NULL, tstamp timestamp without time zone DEFAULT now() NOT NULL)`,
		`INSERT INTO public.goose_db_version (version_id, is_applied) VALUES (0, true), (1, true)`,
	} {
		if err := database.Exec(statement).Error; err != nil {
			t.Fatalf("prepare version one schema: %v", err)
		}
	}

	if _, err := migrations.Up(t.Context(), databaseSQL); err != nil {
		t.Fatalf("apply credit purchase migration: %v", err)
	}

	for _, table := range []string{"credit_purchases", "billing_payment_methods"} {
		var exists bool
		if err := database.Raw(`SELECT to_regclass(?) IS NOT NULL`, "public."+table).Scan(&exists).Error; err != nil {
			t.Fatalf("check %s: %v", table, err)
		}
		if !exists {
			t.Fatalf("migration did not create %s", table)
		}
	}

	var billingCurrencyExists bool
	if err := database.Raw(`
		SELECT EXISTS (
			SELECT 1 FROM information_schema.columns
			WHERE table_schema = 'public' AND table_name = 'orgs' AND column_name = 'billing_currency'
		)`).Scan(&billingCurrencyExists).Error; err != nil {
		t.Fatalf("check billing currency: %v", err)
	}
	if !billingCurrencyExists {
		t.Fatal("migration did not add orgs.billing_currency")
	}
}

func migrationTestURLs(t *testing.T, baseURL, databaseName string) (string, string) {
	t.Helper()
	parsed, err := url.Parse(baseURL)
	if err != nil {
		t.Fatalf("parse database URL: %v", err)
	}
	maintenance := *parsed
	maintenance.Path = "/postgres"
	database := *parsed
	database.Path = "/" + databaseName
	return maintenance.String(), database.String()
}
