---
runner_api_caddy_acme_email: ops@usehivy.com
runner_api_caddy_service_name: caddy
runner_api_caddy_config_path: /etc/caddy/Caddyfile
runner_api_caddy_env_file: "{{ playbook_dir }}/../.env"
runner_api_caddy_custom_binary: /usr/local/bin/caddy
runner_api_caddy_version: v2.9.1
runner_api_caddy_module: github.com/caddy-dns/vercel
runner_api_caddy_required_env:
  - VERCEL_AUTH_API_TOKEN
runner_api_port: 8081
