apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    hivy.io/environment: production
    hivy.io/apply-phase: foundation
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted

