apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: nango-postgres
  labels:
    app.kubernetes.io/name: nango-postgres
    app.kubernetes.io/component: database
    hivy.io/apply-phase: data
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-standard-trixie@sha256:06d950644d127249699c1468d0ffad7e44c34daa11688b0e966dec947eb043c4
  enableSuperuserAccess: false
  primaryUpdateStrategy: unsupervised
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: nango-postgres-backup
  bootstrap:
    initdb:
      database: nango
      owner: nango
      secret:
        name: nango-postgres-app
  postgresql:
    parameters:
      max_connections: "200"
      max_locks_per_transaction: "256"
      shared_buffers: 512MB
  storage:
    storageClass: longhorn
    size: 10Gi
    resizeInUseVolumes: true
  resources:
    requests:
      cpu: 10m
      memory: 768Mi
    limits:
      cpu: "2"
      memory: 3Gi
  monitoring:
    enablePodMonitor: false
---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: nango-postgres-backup
  labels:
    app.kubernetes.io/name: nango-postgres
    app.kubernetes.io/component: backup
    hivy.io/apply-phase: data
spec:
  retentionPolicy: 30d
  configuration:
    destinationPath: s3://usehivy-prod-pg-nango/postgres
    endpointURL: https://hel1.your-objectstorage.com
    s3Credentials:
      accessKeyId:
        name: nango-postgres-backup-s3
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: nango-postgres-backup-s3
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
      maxParallel: 2
    data:
      compression: gzip
      jobs: 2
  instanceSidecarConfiguration:
    resources:
      requests:
        cpu: 5m
        memory: 32Mi
      limits:
        cpu: 500m
        memory: 512Mi
    env:
      - name: AWS_REQUEST_CHECKSUM_CALCULATION
        value: when_required
      - name: AWS_RESPONSE_CHECKSUM_VALIDATION
        value: when_required
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nango-postgres-daily
  labels:
    app.kubernetes.io/name: nango-postgres
    app.kubernetes.io/component: backup
    hivy.io/apply-phase: data
spec:
  schedule: "0 30 2 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: nango-postgres
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
