package registry

// theGridProvider mirrors The Grid's authenticated GET /v1/models directory
// from 2026-07-24. The Grid instruments are stable quality contracts whose
// underlying supplier model may change between requests.
//
// Costs are the published per-million-token instrument prices captured from
// https://thegrid.ai/instruments on 2026-07-24. They are a fallback for streamed
// responses; non-stream responses can carry The Grid's request-level estimated
// cost, which billing prefers over this moving market-price snapshot.
var theGridProvider = Provider{
	ID:   "thegrid",
	Name: "The Grid",
	API:  "https://api.thegrid.ai/v1",
	Doc:  "https://thegrid.ai/docs/api-reference/consumption-api",
	Models: map[string]Model{
		"agent-max": {
			ID:               "agent-max",
			Name:             "The Grid: Agent Max",
			Family:           "agent",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-05-04",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.709, Output: 1.709, CacheRead: 1.709},
			Limit:            &Limit{Context: 1000000, Output: 131072},
			Description:      "Frontier-tier agents for autonomous work, deep tool chains, long-horizon research, and high-stakes automation.",
		},
		"agent-prime": {
			ID:               "agent-prime",
			Name:             "The Grid: Agent Prime",
			Family:           "agent",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-05-04",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.120, Output: 0.120, CacheRead: 0.120},
			Limit:            &Limit{Context: 196608, Output: 131072},
			Description:      "The production default for daily agent work, production agent loops, multi-step tool chains, and planning.",
		},
		"agent-standard": {
			ID:               "agent-standard",
			Name:             "The Grid: Agent Standard",
			Family:           "agent",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-05-04",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.035, Output: 0.035, CacheRead: 0.035},
			Limit:            &Limit{Context: 128000, Output: 65536},
			Description:      "Price-optimized, high-throughput agents for orchestration glue, routing, tool selection, and high-volume single-purpose agents.",
		},
		"bytedance-pro-latest": {
			ID:               "bytedance-pro-latest",
			Name:             "The Grid: ByteDance Pro Latest",
			Family:           "lab",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-07-06",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.220, Output: 0.220, CacheRead: 0.220},
			Limit:            &Limit{Context: 262144, Output: 131072},
			Description:      "Lab latest market for ByteDance Pro supply. The route follows the latest qualifying model and supplier.",
		},
		"claude-opus-latest": {
			ID:               "claude-opus-latest",
			Name:             "The Grid: Claude Opus Latest",
			Family:           "lab",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-07-06",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.709, Output: 1.709, CacheRead: 1.709},
			Limit:            &Limit{Context: 1000000, Output: 128000},
			Description:      "Lab latest market for Claude Opus frontier supply. The route follows the latest qualifying model and supplier.",
		},
		"code-max": {
			ID:               "code-max",
			Name:             "The Grid: Code Max",
			Family:           "code",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-05-04",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.709, Output: 1.709, CacheRead: 1.709},
			Limit:            &Limit{Context: 1000000, Output: 131072},
			Description:      "Frontier-tier code for full-repository analysis, complex debugging, and large multi-file refactors.",
		},
		"code-prime": {
			ID:               "code-prime",
			Name:             "The Grid: Code Prime",
			Family:           "code",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-05-04",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.120, Output: 0.120, CacheRead: 0.120},
			Limit:            &Limit{Context: 196608, Output: 131072},
			Description:      "The production default for daily coding work, interactive development, debugging, and feature implementation.",
		},
		"code-standard": {
			ID:               "code-standard",
			Name:             "The Grid: Code Standard",
			Family:           "code",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-05-04",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.035, Output: 0.035, CacheRead: 0.035},
			Limit:            &Limit{Context: 128000, Output: 65536},
			Description:      "Price-optimized, high-throughput code for autocomplete, linting, batch edits, and boilerplate generation.",
		},
		"deepseek-pro-latest": {
			ID:               "deepseek-pro-latest",
			Name:             "The Grid: DeepSeek Pro Latest",
			Family:           "lab",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-07-06",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.444, Output: 0.444, CacheRead: 0.444},
			Limit:            &Limit{Context: 1000000, Output: 384000},
			Description:      "Lab latest market for DeepSeek Pro supply. The route follows the latest qualifying model and supplier.",
		},
		"gemini-pro-latest": {
			ID:               "gemini-pro-latest",
			Name:             "The Grid: Gemini Pro Latest",
			Family:           "lab",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-07-06",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.656, Output: 0.656, CacheRead: 0.656},
			Limit:            &Limit{Context: 1000000, Output: 65536},
			Description:      "Lab latest market for Gemini Pro frontier supply. The route follows the latest qualifying model and supplier.",
		},
		"glm-latest": {
			ID:               "glm-latest",
			Name:             "The Grid: GLM Latest",
			Family:           "lab",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-07-06",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.355, Output: 0.355, CacheRead: 0.355},
			Limit:            &Limit{Context: 1000000, Output: 128000},
			Description:      "Lab latest market for GLM supply. The route follows the latest qualifying model and supplier.",
		},
		"gpt-sol-latest": {
			ID:               "gpt-sol-latest",
			Name:             "The Grid: GPT Sol Latest",
			Family:           "lab",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-07-06",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.821, Output: 1.821, CacheRead: 1.821},
			Limit:            &Limit{Context: 1000000, Output: 128000},
			Description:      "Lab latest market for GPT frontier supply. The route follows the latest qualifying model and supplier.",
		},
		"kimi-latest": {
			ID:               "kimi-latest",
			Name:             "The Grid: Kimi Latest",
			Family:           "lab",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-07-06",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.000, Output: 1.000, CacheRead: 1.000},
			Limit:            &Limit{Context: 262144, Output: 131072},
			Description:      "Lab latest market for Kimi supply. The route follows the latest qualifying model and supplier.",
		},
		"minimax-latest": {
			ID:               "minimax-latest",
			Name:             "The Grid: MiniMax Latest",
			Family:           "lab",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-07-06",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.118, Output: 0.118, CacheRead: 0.118},
			Limit:            &Limit{Context: 1000000, Output: 512000},
			Description:      "Lab latest market for MiniMax supply. The route follows the latest qualifying model and supplier.",
		},
		"text-max": {
			ID:               "text-max",
			Name:             "The Grid: Text Max",
			Family:           "text",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-02-26",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.709, Output: 1.709, CacheRead: 1.709},
			Limit:            &Limit{Context: 1000000, Output: 131072},
			Description:      "Frontier-tier text for high-stakes reasoning and long-context synthesis across many documents.",
		},
		"text-prime": {
			ID:               "text-prime",
			Name:             "The Grid: Text Prime",
			Family:           "text",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-02-26",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.120, Output: 0.120, CacheRead: 0.120},
			Limit:            &Limit{Context: 196608, Output: 131072},
			Description:      "The production default for everyday text generation, RAG, drafting, summarization, and analysis.",
		},
		"text-standard": {
			ID:               "text-standard",
			Name:             "The Grid: Text Standard",
			Family:           "text",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-02-26",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.035, Output: 0.035, CacheRead: 0.035},
			Limit:            &Limit{Context: 128000, Output: 65536},
			Description:      "Price-optimized, high-throughput text for classification, routing, batch summarization, and pipeline work.",
		},
	},
}
