package registry

// novitaProvider is a snapshot of Novita's authenticated GET /openai/v1/models
// response from 2026-07-23, limited to active text-output chat models. Six
// internal/test-only directory entries are intentionally excluded. Novita's
// integer prices are converted to USD per million tokens.
var novitaProvider = Provider{
	ID:   "novita",
	Name: "Novita AI",
	API:  "https://api.novita.ai/openai/v1",
	Doc:  "https://novita.ai/docs/guides/llm-api",
	Models: map[string]Model{
		"Sao10K/L3-8B-Stheno-v3.2": {
			ID: "Sao10K/L3-8B-Stheno-v3.2", Name: "L3 8B Stheno V3.2",
			ToolCall:    true,
			ReleaseDate: "2024-11-29",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.05, Output: 0.05, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 8192, Output: 32000},
		},
		"baichuan/baichuan-m2-32b": {
			ID: "baichuan/baichuan-m2-32b", Name: "BaiChuan M2 32B",
			ReleaseDate: "2025-08-13",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.07, Output: 0.07, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 131072, Output: 131072},
		},
		"baidu/cobuddy": {
			ID: "baidu/cobuddy", Name: "CoBuddy",
			Reasoning:   true,
			ToolCall:    true,
			ReleaseDate: "2026-06-03",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.28, Output: 1.13, CacheRead: 0.07, CacheWrite: 0},
			Limit:       &Limit{Context: 131072, Output: 65536},
		},
		"baidu/ernie-4.5-21B-a3b": {
			ID: "baidu/ernie-4.5-21B-a3b", Name: "ERNIE 4.5 21B A3B",
			ToolCall:    true,
			ReleaseDate: "2025-06-30",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.07, Output: 0.28, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 120000, Output: 8000},
		},
		"baidu/ernie-4.5-vl-424b-a47b": {
			ID: "baidu/ernie-4.5-vl-424b-a47b", Name: "ERNIE 4.5 VL 424B A47B",
			Reasoning:   true,
			ReleaseDate: "2025-06-30",
			Modalities:  &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.42, Output: 1.25, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 123000, Output: 16000},
		},
		"deepseek/deepseek-ocr": {
			ID: "deepseek/deepseek-ocr", Name: "DeepSeek-OCR",
			ReleaseDate: "2025-10-24",
			Modalities:  &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.03, Output: 0.03, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 8192, Output: 8192},
		},
		"deepseek/deepseek-ocr-2": {
			ID: "deepseek/deepseek-ocr-2", Name: "DeepSeek-OCR 2",
			ReleaseDate: "2026-01-27",
			Modalities:  &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.03, Output: 0.03, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 8192, Output: 8192},
		},
		"deepseek/deepseek-r1": {
			ID: "deepseek/deepseek-r1", Name: "DeepSeek R1",
			Reasoning:   true,
			ToolCall:    true,
			ReleaseDate: "2025-01-26",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 4, Output: 4, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 64000, Output: 16000},
		},
		"deepseek/deepseek-r1-0528": {
			ID: "deepseek/deepseek-r1-0528", Name: "DeepSeek R1 0528",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-05-28",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.7, Output: 2.5, CacheRead: 0.35, CacheWrite: 0},
			Limit:            &Limit{Context: 163840, Output: 32768},
		},
		"deepseek/deepseek-r1-0528-qwen3-8b": {
			ID: "deepseek/deepseek-r1-0528-qwen3-8b", Name: "DeepSeek R1 0528 Qwen3 8B",
			ReleaseDate: "2025-05-29",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.06, Output: 0.09, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 128000, Output: 32000},
		},
		"deepseek/deepseek-r1-distill-llama-70b": {
			ID: "deepseek/deepseek-r1-distill-llama-70b", Name: "DeepSeek R1 Distill LLama 70B",
			Reasoning:   true,
			ReleaseDate: "2025-01-27",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.8, Output: 0.8, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 8192, Output: 8192},
		},
		"deepseek/deepseek-r1-turbo": {
			ID: "deepseek/deepseek-r1-turbo", Name: "DeepSeek R1 (Turbo)\t",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-03-05",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.7, Output: 2.5, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 64000, Output: 16000},
		},
		"deepseek/deepseek-r1/community": {
			ID: "deepseek/deepseek-r1/community", Name: "DeepSeek R1",
			Reasoning:   true,
			ToolCall:    true,
			ReleaseDate: "2025-02-14",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 4, Output: 4, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 64000, Output: 8000},
		},
		"deepseek/deepseek-v3-0324": {
			ID: "deepseek/deepseek-v3-0324", Name: "DeepSeek V3 0324",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-03-25",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.27, Output: 1.12, CacheRead: 0.135, CacheWrite: 0},
			Limit:            &Limit{Context: 163840, Output: 65536},
		},
		"deepseek/deepseek-v3-turbo": {
			ID: "deepseek/deepseek-v3-turbo", Name: "DeepSeek V3 (Turbo)\t",
			ToolCall:    true,
			ReleaseDate: "2025-03-05",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.4, Output: 1.3, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 64000, Output: 16000},
		},
		"deepseek/deepseek-v3.1": {
			ID: "deepseek/deepseek-v3.1", Name: "DeepSeek V3.1",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-08-21",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.27, Output: 1, CacheRead: 0.135, CacheWrite: 0},
			Limit:            &Limit{Context: 131072, Output: 32768},
		},
		"deepseek/deepseek-v3.1-terminus": {
			ID: "deepseek/deepseek-v3.1-terminus", Name: "Deepseek V3.1 Terminus",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-09-22",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.27, Output: 1, CacheRead: 0.135, CacheWrite: 0},
			Limit:            &Limit{Context: 131072, Output: 32768},
		},
		"deepseek/deepseek-v3.2": {
			ID: "deepseek/deepseek-v3.2", Name: "Deepseek V3.2",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-12-01",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.269, Output: 0.4, CacheRead: 0.1345, CacheWrite: 0},
			Limit:            &Limit{Context: 163840, Output: 65536},
		},
		"deepseek/deepseek-v3.2-exp": {
			ID: "deepseek/deepseek-v3.2-exp", Name: "Deepseek V3.2 Exp",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-09-29",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.27, Output: 0.41, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 163840, Output: 65536},
		},
		"deepseek/deepseek-v3/community": {
			ID: "deepseek/deepseek-v3/community", Name: "DeepSeek V3",
			ToolCall:    true,
			ReleaseDate: "2025-02-14",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.89, Output: 0.89, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 64000, Output: 8000},
		},
		"deepseek/deepseek-v4-flash": {
			ID: "deepseek/deepseek-v4-flash", Name: "Deepseek V4 Flash",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-04-24",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.14, Output: 0.28, CacheRead: 0.028, CacheWrite: 0},
			Limit:            &Limit{Context: 1048576, Output: 393216},
		},
		"deepseek/deepseek-v4-pro": {
			ID: "deepseek/deepseek-v4-pro", Name: "Deepseek V4 Pro",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-04-24",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.6, Output: 3.2, CacheRead: 0.135, CacheWrite: 0},
			Limit:            &Limit{Context: 1048576, Output: 393216},
		},
		"deepseek/deepseek_v3": {
			ID: "deepseek/deepseek_v3", Name: "DeepSeek V3",
			ToolCall:    true,
			ReleaseDate: "2025-01-15",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.89, Output: 0.89, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 64000, Output: 16000},
		},
		"google/gemma-3-12b-it": {
			ID: "google/gemma-3-12b-it", Name: "Gemma3 12B",
			ReleaseDate: "2025-09-04",
			Modalities:  &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.05, Output: 0.1, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 131072, Output: 8192},
		},
		"google/gemma-3-27b-it": {
			ID: "google/gemma-3-27b-it", Name: "Gemma 3 27B",
			ReleaseDate: "2025-03-25",
			Modalities:  &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.119, Output: 0.2, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 98304, Output: 16384},
		},
		"google/gemma-4-26b-a4b-it": {
			ID: "google/gemma-4-26b-a4b-it", Name: "Gemma 4 26B A4B",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-04-02",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.13, Output: 0.4, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 131072},
		},
		"google/gemma-4-31b-it": {
			ID: "google/gemma-4-31b-it", Name: "Gemma 4 31B",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-04-02",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.14, Output: 0.4, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 131072},
		},
		"gryphe/mythomax-l2-13b": {
			ID: "gryphe/mythomax-l2-13b", Name: "Mythomax L2 13B",
			ReleaseDate: "2024-04-25",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.09, Output: 0.09, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 4096, Output: 3200},
		},
		"inclusionai/ling-2.6-1t": {
			ID: "inclusionai/ling-2.6-1t", Name: "Ling-2.6-1T",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-04-23",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.3, Output: 2.5, CacheRead: 0.06, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 32768},
		},
		"inclusionai/ling-2.6-flash": {
			ID: "inclusionai/ling-2.6-flash", Name: "Ling-2.6-flash",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-04-24",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.1, Output: 0.3, CacheRead: 0.02, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 32768},
		},
		"inclusionai/ling-3.0-flash": {
			ID: "inclusionai/ling-3.0-flash", Name: "Ling-3.0-flash",
			Reasoning:   true,
			ToolCall:    true,
			ReleaseDate: "2026-07-22",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 262144, Output: 32768},
		},
		"inclusionai/ring-2.6-1t": {
			ID: "inclusionai/ring-2.6-1t", Name: "Ring-2.6-1T",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-05-08",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.3, Output: 2.5, CacheRead: 0.06, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 65536},
		},
		"kwaipilot/kat-coder-pro": {
			ID: "kwaipilot/kat-coder-pro", Name: "Kat Coder Pro",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-01-05",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.3, Output: 1.2, CacheRead: 0.06, CacheWrite: 0},
			Limit:            &Limit{Context: 256000, Output: 128000},
		},
		"meta-llama/llama-3.1-8b-instruct": {
			ID: "meta-llama/llama-3.1-8b-instruct", Name: "Llama 3.1 8B Instruct",
			StructuredOutput: true,
			ReleaseDate:      "2024-07-24",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.02, Output: 0.05, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 16384, Output: 16384},
		},
		"meta-llama/llama-3.2-1b-instruct": {
			ID: "meta-llama/llama-3.2-1b-instruct", Name: "Llama 3.2 1B Instruct\t",
			StructuredOutput: true,
			ReleaseDate:      "2024-11-26",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.02, Output: 0.02, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 131000, Output: 32000},
		},
		"meta-llama/llama-3.2-3b-instruct": {
			ID: "meta-llama/llama-3.2-3b-instruct", Name: "Llama 3.2 3B Instruct",
			ReleaseDate: "2024-11-26",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.03, Output: 0.05, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 32768, Output: 32000},
		},
		"meta-llama/llama-3.3-70b-instruct": {
			ID: "meta-llama/llama-3.3-70b-instruct", Name: "Llama 3.3 70B Instruct",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2024-12-07",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.135, Output: 0.4, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 6000, Output: 120000},
		},
		"meta-llama/llama-4-maverick-17b-128e-instruct-fp8": {
			ID: "meta-llama/llama-4-maverick-17b-128e-instruct-fp8", Name: "Llama 4 Maverick Instruct",
			StructuredOutput: true,
			ReleaseDate:      "2025-04-06",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.27, Output: 0.85, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 1048576, Output: 8192},
		},
		"meta-llama/llama-4-scout-17b-16e-instruct": {
			ID: "meta-llama/llama-4-scout-17b-16e-instruct", Name: "Llama 4 Scout Instruct",
			ReleaseDate: "2025-04-06",
			Modalities:  &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.18, Output: 0.59, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 131072, Output: 131072},
		},
		"microsoft/wizardlm-2-8x22b": {
			ID: "microsoft/wizardlm-2-8x22b", Name: "Wizardlm 2 8x22B",
			StructuredOutput: true,
			ReleaseDate:      "2024-04-24",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.62, Output: 0.62, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 65535, Output: 8000},
		},
		"minimax/m2-her": {
			ID: "minimax/m2-her", Name: "M2-her",
			ReleaseDate: "2026-01-22",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0, Output: 0, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 32000},
		},
		"minimax/minimax-m2": {
			ID: "minimax/minimax-m2", Name: "MiniMax-M2",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-10-27",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.3, Output: 1.2, CacheRead: 0.03, CacheWrite: 0},
			Limit:            &Limit{Context: 204800, Output: 131072},
		},
		"minimax/minimax-m2.1": {
			ID: "minimax/minimax-m2.1", Name: "Minimax M2.1",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-12-23",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.3, Output: 1.2, CacheRead: 0.03, CacheWrite: 0},
			Limit:            &Limit{Context: 204800, Output: 131072},
		},
		"minimax/minimax-m2.5": {
			ID: "minimax/minimax-m2.5", Name: "MiniMax M2.5",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-02-12",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.3, Output: 1.2, CacheRead: 0.03, CacheWrite: 0},
			Limit:            &Limit{Context: 204800, Output: 131100},
		},
		"minimax/minimax-m2.5-highspeed": {
			ID: "minimax/minimax-m2.5-highspeed", Name: "MiniMax M2.5-highspeed",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-03-02",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.6, Output: 2.4, CacheRead: 0.03, CacheWrite: 0},
			Limit:            &Limit{Context: 204800, Output: 131100},
		},
		"minimax/minimax-m2.7": {
			ID: "minimax/minimax-m2.7", Name: "MiniMax M2.7",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-03-17",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.3, Output: 1.2, CacheRead: 0.06, CacheWrite: 0},
			Limit:            &Limit{Context: 204800, Output: 131072},
		},
		"minimax/minimax-m2.7-highspeed": {
			ID: "minimax/minimax-m2.7-highspeed", Name: "MiniMax M2.7-highspeed",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-04-02",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.6, Output: 2.4, CacheRead: 0.06, CacheWrite: 0},
			Limit:            &Limit{Context: 204800, Output: 131072},
		},
		"minimax/minimax-m3": {
			ID: "minimax/minimax-m3", Name: "MiniMax M3",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-06-01",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.3, Output: 1.2, CacheRead: 0.06, CacheWrite: 0, Tiers: []CostTier{{MinContext: 524288, Input: 0.6, Output: 2.4, CacheRead: 0.12, CacheWrite: 0}}},
			Limit:            &Limit{Context: 1000000, Output: 131072},
		},
		"minimaxai/minimax-m1-80k": {
			ID: "minimaxai/minimax-m1-80k", Name: "MiniMax M1",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-06-17",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.55, Output: 2.2, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 1000000, Output: 40000},
		},
		"mistralai/mistral-nemo": {
			ID: "mistralai/mistral-nemo", Name: "Mistral Nemo",
			StructuredOutput: true,
			ReleaseDate:      "2024-07-30",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.04, Output: 0.17, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 60288, Output: 16000},
		},
		"moonshotai/kimi-k2-0905": {
			ID: "moonshotai/kimi-k2-0905", Name: "Kimi K2 0905",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-09-05",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.6, Output: 2.5, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 100352},
		},
		"moonshotai/kimi-k2-instruct": {
			ID: "moonshotai/kimi-k2-instruct", Name: "Kimi K2 Instruct",
			ToolCall:    true,
			ReleaseDate: "2025-07-11",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.57, Output: 2.3, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 131072, Output: 100352},
		},
		"moonshotai/kimi-k2-thinking": {
			ID: "moonshotai/kimi-k2-thinking", Name: "Kimi K2 Thinking",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-11-07",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.6, Output: 2.5, CacheRead: 0.15, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 100352},
		},
		"moonshotai/kimi-k2.5": {
			ID: "moonshotai/kimi-k2.5", Name: "Kimi K2.5",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-01-27",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.6, Output: 3, CacheRead: 0.1, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 262144},
		},
		"moonshotai/kimi-k2.6": {
			ID: "moonshotai/kimi-k2.6", Name: "Kimi K2.6",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-04-20",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.8, Output: 3.4, CacheRead: 0.16, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 262144},
		},
		"moonshotai/kimi-k2.7-code": {
			ID: "moonshotai/kimi-k2.7-code", Name: "Kimi K2.7 Code",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-06-12",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.95, Output: 4, CacheRead: 0.19, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 262144},
		},
		"moonshotai/kimi-k3": {
			ID: "moonshotai/kimi-k3", Name: "Kimi K3",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-07-16",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 3, Output: 15, CacheRead: 0.3, CacheWrite: 0},
			Limit:            &Limit{Context: 1048576, Output: 1048576},
		},
		"nousresearch/hermes-2-pro-llama-3-8b": {
			ID: "nousresearch/hermes-2-pro-llama-3-8b", Name: "Hermes 2 Pro Llama 3 8B",
			StructuredOutput: true,
			ReleaseDate:      "2024-06-27",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.14, Output: 0.14, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 8192, Output: 8192},
		},
		"nvidia/nemotron-3-nano-30b-a3b": {
			ID: "nvidia/nemotron-3-nano-30b-a3b", Name: "Nemotron 3 Nano 30B A3B",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-06-09",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.05, Output: 0.2, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 32768},
		},
		"openai/gpt-oss-120b": {
			ID: "openai/gpt-oss-120b", Name: "OpenAI GPT OSS 120B",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-08-06",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.05, Output: 0.25, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 131072, Output: 32768},
		},
		"openai/gpt-oss-20b": {
			ID: "openai/gpt-oss-20b", Name: "OpenAI: GPT OSS 20B",
			Reasoning:        true,
			StructuredOutput: true,
			ReleaseDate:      "2025-08-06",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.04, Output: 0.15, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 131072, Output: 32768},
		},
		"paddlepaddle/paddleocr-vl": {
			ID: "paddlepaddle/paddleocr-vl", Name: "PaddleOCR-VL",
			ReleaseDate: "2025-10-22",
			Modalities:  &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.02, Output: 0.02, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 16384, Output: 16384},
		},
		"qwen/qwen-2.5-72b-instruct": {
			ID: "qwen/qwen-2.5-72b-instruct", Name: "Qwen 2.5 72B Instruct",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2024-10-15",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.38, Output: 0.4, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 32000, Output: 8192},
		},
		"qwen/qwen-mt-plus": {
			ID: "qwen/qwen-mt-plus", Name: "Qwen MT Plus",
			ReleaseDate: "2025-09-03",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.25, Output: 0.75, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 16384, Output: 8192},
		},
		"qwen/qwen3-235b-a22b-fp8": {
			ID: "qwen/qwen3-235b-a22b-fp8", Name: "Qwen3 235B A22B",
			Reasoning:        true,
			StructuredOutput: true,
			ReleaseDate:      "2025-04-29",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.2, Output: 0.8, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 40960, Output: 20000},
		},
		"qwen/qwen3-235b-a22b-instruct-2507": {
			ID: "qwen/qwen3-235b-a22b-instruct-2507", Name: "Qwen3 235B A22B Instruct 2507",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-07-22",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.09, Output: 0.58, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 131072, Output: 16384},
		},
		"qwen/qwen3-235b-a22b-thinking-2507": {
			ID: "qwen/qwen3-235b-a22b-thinking-2507", Name: "Qwen3 235B A22b Thinking 2507",
			Reasoning:   true,
			ToolCall:    true,
			ReleaseDate: "2025-07-25",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.3, Output: 3, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 131072, Output: 32768},
		},
		"qwen/qwen3-coder-30b-a3b-instruct": {
			ID: "qwen/qwen3-coder-30b-a3b-instruct", Name: "Qwen3 Coder 30b A3B Instruct",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-10-09",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.07, Output: 0.27, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 160000, Output: 32768},
		},
		"qwen/qwen3-coder-480b-a35b-instruct": {
			ID: "qwen/qwen3-coder-480b-a35b-instruct", Name: "Qwen3 Coder 480B A35B Instruct",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-07-23",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.38, Output: 1.55, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 65536},
		},
		"qwen/qwen3-coder-next": {
			ID: "qwen/qwen3-coder-next", Name: "Qwen3 Coder Next",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-02-03",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.2, Output: 1.5, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 65536},
		},
		"qwen/qwen3-max": {
			ID: "qwen/qwen3-max", Name: "Qwen3 Max",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-09-24",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.845, Output: 3.38, CacheRead: 0, CacheWrite: 0, Tiers: []CostTier{{MinContext: 32768, Input: 1.4, Output: 5.64, CacheRead: 0, CacheWrite: 0}, {MinContext: 131072, Input: 2.11, Output: 8.45, CacheRead: 0, CacheWrite: 0}}},
			Limit:            &Limit{Context: 262144, Output: 65536},
		},
		"qwen/qwen3-next-80b-a3b-instruct": {
			ID: "qwen/qwen3-next-80b-a3b-instruct", Name: "Qwen3 Next 80B A3B Instruct",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-09-10",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.15, Output: 1.5, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 131072, Output: 32768},
		},
		"qwen/qwen3-omni-30b-a3b-instruct": {
			ID: "qwen/qwen3-omni-30b-a3b-instruct", Name: "Qwen3 Omni 30B A3B Instruct",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-09-24",
			Modalities:       &Modalities{Input: []string{"text", "video", "audio", "image"}, Output: []string{"text", "audio"}},
			Cost:             &Cost{Input: 0.25, Output: 0.97, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 65536, Output: 16384},
		},
		"qwen/qwen3-omni-30b-a3b-thinking": {
			ID: "qwen/qwen3-omni-30b-a3b-thinking", Name: "Qwen3 Omni 30B A3B Thinking",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-09-24",
			Modalities:       &Modalities{Input: []string{"text", "audio", "video", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.25, Output: 0.97, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 65536, Output: 16384},
		},
		"qwen/qwen3-vl-235b-a22b-instruct": {
			ID: "qwen/qwen3-vl-235b-a22b-instruct", Name: "Qwen3 VL 235B A22B Instruct",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-09-24",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.3, Output: 1.5, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 131072, Output: 32768},
		},
		"qwen/qwen3-vl-235b-a22b-thinking": {
			ID: "qwen/qwen3-vl-235b-a22b-thinking", Name: "Qwen3 VL 235B A22B Thinking",
			Reasoning:   true,
			ToolCall:    true,
			ReleaseDate: "2025-09-24",
			Modalities:  &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.98, Output: 3.95, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 131072, Output: 32768},
		},
		"qwen/qwen3-vl-30b-a3b-instruct": {
			ID: "qwen/qwen3-vl-30b-a3b-instruct", Name: "qwen/qwen3-vl-30b-a3b-instruct",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-10-11",
			Modalities:       &Modalities{Input: []string{"text", "video", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.2, Output: 0.7, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 131072, Output: 32768},
		},
		"qwen/qwen3.5-122b-a10b": {
			ID: "qwen/qwen3.5-122b-a10b", Name: "Qwen3.5-122B-A10B",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-02-26",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.4, Output: 3.2, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 65536},
		},
		"qwen/qwen3.5-27b": {
			ID: "qwen/qwen3.5-27b", Name: "Qwen3.5-27B",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-02-26",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.3, Output: 2.4, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 65536},
		},
		"qwen/qwen3.5-35b-a3b": {
			ID: "qwen/qwen3.5-35b-a3b", Name: "Qwen3.5-35B-A3B",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-02-26",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.25, Output: 2, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 65536},
		},
		"qwen/qwen3.5-397b-a17b": {
			ID: "qwen/qwen3.5-397b-a17b", Name: "Qwen3.5-397B-A17B",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-02-16",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.6, Output: 3.6, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 65536},
		},
		"qwen/qwen3.5-plus": {
			ID: "qwen/qwen3.5-plus", Name: "Qwen3.5-Plus",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-02-16",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.4, Output: 2.4, CacheRead: 0, CacheWrite: 0, Tiers: []CostTier{{MinContext: 256000, Input: 0.5, Output: 3, CacheRead: 0, CacheWrite: 0}}},
			Limit:            &Limit{Context: 1000000, Output: 65536},
		},
		"qwen/qwen3.6-27b": {
			ID: "qwen/qwen3.6-27b", Name: "Qwen3.6-27B",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-04-23",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.6, Output: 3.6, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 65536},
		},
		"qwen/qwen3.6-35b-a3b": {
			ID: "qwen/qwen3.6-35b-a3b", Name: "Qwen3.6-35B-A3B",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-04-21",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.248, Output: 1.485, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 65536},
		},
		"qwen/qwen3.6-plus": {
			ID: "qwen/qwen3.6-plus", Name: "Qwen3.6-Plus",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-04-21",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.5, Output: 3, CacheRead: 0.05, CacheWrite: 0.625, Tiers: []CostTier{{MinContext: 262144, Input: 2, Output: 6, CacheRead: 0.2, CacheWrite: 2.5}}},
			Limit:            &Limit{Context: 1000000, Output: 65536},
		},
		"qwen/qwen3.7-max": {
			ID: "qwen/qwen3.7-max", Name: "Qwen3.7-Max",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-05-21",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.25, Output: 3.75, CacheRead: 0.25, CacheWrite: 0},
			Limit:            &Limit{Context: 1000000, Output: 65536},
		},
		"sao10k/l3-70b-euryale-v2.1": {
			ID: "sao10k/l3-70b-euryale-v2.1", Name: "L3 70B Euryale V2.1\t",
			ToolCall:    true,
			ReleaseDate: "2024-06-18",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 1.48, Output: 1.48, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 8192, Output: 8192},
		},
		"sao10k/l3-8b-lunaris": {
			ID: "sao10k/l3-8b-lunaris", Name: "Sao10k L3 8B Lunaris\t",
			StructuredOutput: true,
			ReleaseDate:      "2024-11-28",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.05, Output: 0.05, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 8192, Output: 8192},
		},
		"sao10k/l31-70b-euryale-v2.2": {
			ID: "sao10k/l31-70b-euryale-v2.2", Name: "L31 70B Euryale V2.2",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2024-09-19",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.48, Output: 1.48, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 8192, Output: 8192},
		},
		"stepfun/step-3.7-flash": {
			ID: "stepfun/step-3.7-flash", Name: "Step 3.7 Flash",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-06-12",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.2, Output: 1.15, CacheRead: 0.04, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 256000},
		},
		"tencent/hy3": {
			ID: "tencent/hy3", Name: "Hy3",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-06-30",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.14, Output: 0.58, CacheRead: 0.035, CacheWrite: 0},
			Limit:            &Limit{Context: 262144, Output: 262144},
		},
		"thudm/glm-4-32b-0414": {
			ID: "thudm/glm-4-32b-0414", Name: "GLM-4-32B-0414",
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-04-16",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.55, Output: 1.66, CacheRead: 0, CacheWrite: 0},
			Limit:            &Limit{Context: 32000, Output: 32000},
		},
		"xiaomimimo/mimo-v2.5": {
			ID: "xiaomimimo/mimo-v2.5", Name: "XiaomiMiMo/MiMo-V2.5",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-05-29",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.168, Output: 0.336, CacheRead: 0.0034, CacheWrite: 0},
			Limit:            &Limit{Context: 1048576, Output: 131072},
		},
		"xiaomimimo/mimo-v2.5-pro": {
			ID: "xiaomimimo/mimo-v2.5-pro", Name: "XiaomiMiMo/MiMo-V2.5-Pro",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-05-06",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.522, Output: 1.044, CacheRead: 0.0043, CacheWrite: 0},
			Limit:            &Limit{Context: 1048576, Output: 131072},
		},
		"zai-org/autoglm-phone-9b-multilingual": {
			ID: "zai-org/autoglm-phone-9b-multilingual", Name: "AutoGLM-Phone-9B-Multilingual",
			ReleaseDate: "2025-12-10",
			Modalities:  &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.035, Output: 0.138, CacheRead: 0, CacheWrite: 0},
			Limit:       &Limit{Context: 65536, Output: 65536},
		},
		"zai-org/glm-4.5-air": {
			ID: "zai-org/glm-4.5-air", Name: "zai-org/glm-4.5-air",
			Reasoning:   true,
			ToolCall:    true,
			ReleaseDate: "2025-10-13",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.13, Output: 0.85, CacheRead: 0.025, CacheWrite: 0},
			Limit:       &Limit{Context: 131072, Output: 98304},
		},
		"zai-org/glm-4.5v": {
			ID: "zai-org/glm-4.5v", Name: "GLM 4.5V",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-08-11",
			Modalities:       &Modalities{Input: []string{"text", "video", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.6, Output: 1.8, CacheRead: 0.11, CacheWrite: 0},
			Limit:            &Limit{Context: 65536, Output: 16384},
		},
		"zai-org/glm-4.6": {
			ID: "zai-org/glm-4.6", Name: "GLM 4.6",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-09-30",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.55, Output: 2.2, CacheRead: 0.11, CacheWrite: 0},
			Limit:            &Limit{Context: 204800, Output: 131072},
		},
		"zai-org/glm-4.6v": {
			ID: "zai-org/glm-4.6v", Name: "GLM 4.6V",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-12-08",
			Modalities:       &Modalities{Input: []string{"text", "video", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.3, Output: 0.9, CacheRead: 0.055, CacheWrite: 0},
			Limit:            &Limit{Context: 131072, Output: 32768},
		},
		"zai-org/glm-4.7": {
			ID: "zai-org/glm-4.7", Name: "GLM-4.7",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2025-12-22",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.6, Output: 2.2, CacheRead: 0.11, CacheWrite: 0},
			Limit:            &Limit{Context: 204800, Output: 131072},
		},
		"zai-org/glm-4.7-flash": {
			ID: "zai-org/glm-4.7-flash", Name: "GLM-4.7-Flash",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-01-19",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.07, Output: 0.4, CacheRead: 0.01, CacheWrite: 0},
			Limit:            &Limit{Context: 200000, Output: 128000},
		},
		"zai-org/glm-4.7-h": {
			ID: "zai-org/glm-4.7-h", Name: "GLM-4.7",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-01-26",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.6, Output: 2.2, CacheRead: 0.11, CacheWrite: 0},
			Limit:            &Limit{Context: 204800, Output: 131072},
		},
		"zai-org/glm-5": {
			ID: "zai-org/glm-5", Name: "GLM-5",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-02-08",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1, Output: 3.2, CacheRead: 0.2, CacheWrite: 0},
			Limit:            &Limit{Context: 202800, Output: 131072},
		},
		"zai-org/glm-5-turbo": {
			ID: "zai-org/glm-5-turbo", Name: "GLM-5-Turbo",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-03-26",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.2, Output: 4, CacheRead: 0.24, CacheWrite: 0},
			Limit:            &Limit{Context: 202800, Output: 131072},
		},
		"zai-org/glm-5.1": {
			ID: "zai-org/glm-5.1", Name: "GLM-5.1",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-04-07",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.38, Output: 4.4, CacheRead: 0.26, CacheWrite: 0},
			Limit:            &Limit{Context: 204800, Output: 131072},
		},
		"zai-org/glm-5.2": {
			ID: "zai-org/glm-5.2", Name: "GLM 5.2",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-06-12",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.4, Output: 4.4, CacheRead: 0.26, CacheWrite: 0},
			Limit:            &Limit{Context: 1048576, Output: 131072},
		},
		"zai-org/glm-5v-turbo": {
			ID: "zai-org/glm-5v-turbo", Name: "GLM-5V-Turbo",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			ReleaseDate:      "2026-04-02",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.2, Output: 4, CacheRead: 0.24, CacheWrite: 0},
			Limit:            &Limit{Context: 204800, Output: 131072},
		},
	},
}
