package registry

// togetherProvider is a snapshot of Together AI's authenticated GET /v1/models
// response from 2026-07-23. It contains every entry whose live directory type
// is chat. Prices are the directory's USD rates per million tokens. Capability
// and output-limit metadata is enriched from the checked-in models.dev snapshot
// when available; Together's directory remains authoritative for IDs, names,
// context lengths, and prices.
var togetherProvider = Provider{
	ID:   "together",
	Name: "Together AI",
	API:  "https://api.together.ai/v1",
	Doc:  "https://docs.together.ai/docs/serverless/models",
	Models: map[string]Model{
		"Hcompany/Holo3-35B-A3B": {
			ID:         "Hcompany/Holo3-35B-A3B",
			Name:       "Holo3 35B A3b",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"LiquidAI/LFM2.5-8B-A1B": {
			ID:         "LiquidAI/LFM2.5-8B-A1B",
			Name:       "LFM2.5-8B-A1B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.03, Output: 0.12, CacheRead: 0.03},
			Limit:      &Limit{Context: 128000, Output: 0},
		},
		"MiniMaxAI/MiniMax-M1-40k": {
			ID:         "MiniMaxAI/MiniMax-M1-40k",
			Name:       "Minimax M1 40K",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 1048576, Output: 0},
		},
		"MiniMaxAI/MiniMax-M1-80k": {
			ID:         "MiniMaxAI/MiniMax-M1-80k",
			Name:       "Minimax M1 80K",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 1048576, Output: 0},
		},
		"MiniMaxAI/MiniMax-M2": {
			ID:         "MiniMaxAI/MiniMax-M2",
			Name:       "MiniMax M2",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 196608, Output: 0},
		},
		"MiniMaxAI/MiniMax-M2.5-FP4": {
			ID:         "MiniMaxAI/MiniMax-M2.5-FP4",
			Name:       "MiniMax M2.5 FP4",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 8192, Output: 0},
		},
		"MiniMaxAI/MiniMax-M2.7": {
			ID:               "MiniMaxAI/MiniMax-M2.7",
			Name:             "MiniMax M2.7 FP4",
			Family:           "minimax",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			OpenWeights:      true,
			ReleaseDate:      "2026-03-18",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.3, Output: 1.2, CacheRead: 0.06},
			Limit:            &Limit{Context: 196608, Output: 131072},
		},
		"MiniMaxAI/MiniMax-M3": {
			ID:               "MiniMaxAI/MiniMax-M3",
			Name:             "MiniMax M3",
			Family:           "minimax",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			OpenWeights:      true,
			ReleaseDate:      "2026-06-12",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.3, Output: 1.2, CacheRead: 0.06},
			Limit:            &Limit{Context: 524288, Output: 250000},
		},
		"NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO": {
			ID:         "NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO",
			Name:       "Nous Hermes 2 Mixtral 8X7B Dpo",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.6, Output: 0.6, CacheRead: 0.6},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"Qwen/QwQ-32B": {
			ID:         "Qwen/QwQ-32B",
			Name:       "Qwen QwQ-32B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 1.2, Output: 1.2, CacheRead: 1.2},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"Qwen/Qwen2-1.5B-Instruct": {
			ID:         "Qwen/Qwen2-1.5B-Instruct",
			Name:       "Qwen 2 Instruct (1.5B)",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.02, Output: 0.02, CacheRead: 0.02},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"Qwen/Qwen2-72B-Instruct": {
			ID:         "Qwen/Qwen2-72B-Instruct",
			Name:       "Qwen2 72B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.9, Output: 0.9, CacheRead: 0.9},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"Qwen/Qwen2-VL-72B-Instruct": {
			ID:         "Qwen/Qwen2-VL-72B-Instruct",
			Name:       "Qwen2-VL (72B) Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 1.2, Output: 1.2, CacheRead: 1.2},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"Qwen/Qwen2.5-1.5B": {
			ID:         "Qwen/Qwen2.5-1.5B",
			Name:       "Qwen2.5 1.5B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"Qwen/Qwen2.5-1.5B-Instruct": {
			ID:         "Qwen/Qwen2.5-1.5B-Instruct",
			Name:       "Qwen2.5 1.5B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"Qwen/Qwen2.5-14B": {
			ID:         "Qwen/Qwen2.5-14B",
			Name:       "Qwen2.5 14B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"Qwen/Qwen2.5-14B-Instruct": {
			ID:         "Qwen/Qwen2.5-14B-Instruct",
			Name:       "Qwen 2.5 14B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.8, Output: 0.8, CacheRead: 0.8},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"Qwen/Qwen2.5-32B": {
			ID:         "Qwen/Qwen2.5-32B",
			Name:       "Qwen2.5 32B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"Qwen/Qwen2.5-32B-Instruct": {
			ID:         "Qwen/Qwen2.5-32B-Instruct",
			Name:       "Qwen2.5 32B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"Qwen/Qwen2.5-3B-Instruct": {
			ID:         "Qwen/Qwen2.5-3B-Instruct",
			Name:       "Qwen2.5 3B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"Qwen/Qwen2.5-72B": {
			ID:         "Qwen/Qwen2.5-72B",
			Name:       "Qwen2.5 72B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"Qwen/Qwen2.5-72B-Instruct": {
			ID:         "Qwen/Qwen2.5-72B-Instruct",
			Name:       "Qwen2.5 72B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 1.2, Output: 1.2, CacheRead: 1.2},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"Qwen/Qwen2.5-72B-Instruct-Turbo": {
			ID:         "Qwen/Qwen2.5-72B-Instruct-Turbo",
			Name:       "Qwen2.5 72B Instruct Turbo",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 1.2, Output: 1.2, CacheRead: 1.2},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"Qwen/Qwen2.5-7B": {
			ID:         "Qwen/Qwen2.5-7B",
			Name:       "Qwen2.5 7B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"Qwen/Qwen2.5-7B-Instruct": {
			ID:         "Qwen/Qwen2.5-7B-Instruct",
			Name:       "Qwen2.5 7B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"Qwen/Qwen2.5-7B-Instruct-Turbo": {
			ID:               "Qwen/Qwen2.5-7B-Instruct-Turbo",
			Name:             "Qwen2.5 7B Instruct Turbo",
			Family:           "qwen",
			ToolCall:         true,
			StructuredOutput: true,
			OpenWeights:      true,
			ReleaseDate:      "2024-09-19",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.3, Output: 0.3, CacheRead: 0.3},
			Limit:            &Limit{Context: 32768, Output: 32768},
		},
		"Qwen/Qwen2.5-Coder-32B-Instruct": {
			ID:         "Qwen/Qwen2.5-Coder-32B-Instruct",
			Name:       "Qwen 2.5 Coder 32B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.8, Output: 0.8, CacheRead: 0.8},
			Limit:      &Limit{Context: 16384, Output: 0},
		},
		"Qwen/Qwen2.5-VL-72B-Instruct": {
			ID:         "Qwen/Qwen2.5-VL-72B-Instruct",
			Name:       "Qwen2.5-VL (72B) Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 1.95, Output: 8, CacheRead: 1.95},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"Qwen/Qwen3-0.6B": {
			ID:         "Qwen/Qwen3-0.6B",
			Name:       "Qwen3 0.6B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 40960, Output: 0},
		},
		"Qwen/Qwen3-1.7B": {
			ID:         "Qwen/Qwen3-1.7B",
			Name:       "Qwen3 1.7B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 40960, Output: 0},
		},
		"Qwen/Qwen3-14B": {
			ID:         "Qwen/Qwen3-14B",
			Name:       "Qwen3 14B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 2048, Output: 0},
		},
		"Qwen/Qwen3-235B-A22B-Instruct-2507-FP8": {
			ID:         "Qwen/Qwen3-235B-A22B-Instruct-2507-FP8",
			Name:       "Qwen3 235B A22b Instruct 2507 Fp8",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3-30B-A3B": {
			ID:         "Qwen/Qwen3-30B-A3B",
			Name:       "Qwen3 30B A3b",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 40960, Output: 0},
		},
		"Qwen/Qwen3-30B-A3B-Instruct-2507-Lora": {
			ID:         "Qwen/Qwen3-30B-A3B-Instruct-2507-Lora",
			Name:       "Qwen3 30B A3B Instruct 2507 Lora",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3-32B": {
			ID:         "Qwen/Qwen3-32B",
			Name:       "Qwen3 32B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 40960, Output: 0},
		},
		"Qwen/Qwen3-4B-Instruct-2507": {
			ID:         "Qwen/Qwen3-4B-Instruct-2507",
			Name:       "Qwen3 4B Instruct 2507",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3-8B": {
			ID:         "Qwen/Qwen3-8B",
			Name:       "Qwen3 8B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 40960, Output: 0},
		},
		"Qwen/Qwen3-8B-Lora": {
			ID:         "Qwen/Qwen3-8B-Lora",
			Name:       "Qwen3 8B Lora",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 40960, Output: 0},
		},
		"Qwen/Qwen3-Coder-30B-A3B-Instruct": {
			ID:         "Qwen/Qwen3-Coder-30B-A3B-Instruct",
			Name:       "Qwen3 Coder 30B A3b Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8": {
			ID:          "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8",
			Name:        "Qwen3 Coder 480B A35B Instruct Fp8",
			Family:      "qwen",
			ToolCall:    true,
			OpenWeights: true,
			Knowledge:   "2025-04",
			ReleaseDate: "2025-07-23",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 2, Output: 2, CacheRead: 2},
			Limit:       &Limit{Context: 262144, Output: 262144},
		},
		"Qwen/Qwen3-Coder-Next-FP8": {
			ID:          "Qwen/Qwen3-Coder-Next-FP8",
			Name:        "Qwen3 Coder Next Fp8",
			Family:      "qwen",
			ToolCall:    true,
			OpenWeights: true,
			Knowledge:   "2026-02-03",
			ReleaseDate: "2026-02-03",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.5, Output: 1.2, CacheRead: 0.5},
			Limit:       &Limit{Context: 262144, Output: 262144},
		},
		"Qwen/Qwen3-Next-80B-A3B-Instruct": {
			ID:         "Qwen/Qwen3-Next-80B-A3B-Instruct",
			Name:       "Qwen3 Next 80B A3b Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.15, Output: 1.5, CacheRead: 0.15},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3-Next-80B-A3B-Instruct-FP8": {
			ID:         "Qwen/Qwen3-Next-80B-A3B-Instruct-FP8",
			Name:       "Qwen3 Next 80B A3b Instruct Fp8",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
		},
		"Qwen/Qwen3-Next-80B-A3B-Thinking": {
			ID:         "Qwen/Qwen3-Next-80B-A3B-Thinking",
			Name:       "Qwen3 Next 80B A3b Thinking",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.15, Output: 1.5, CacheRead: 0.15},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3-VL-235B-A22B-Instruct-FP8": {
			ID:         "Qwen/Qwen3-VL-235B-A22B-Instruct-FP8",
			Name:       "Qwen3-VL-235B-A22B-Instruct-FP8",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3-VL-32B-Instruct": {
			ID:         "Qwen/Qwen3-VL-32B-Instruct",
			Name:       "Qwen3-VL-32B-Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.5, Output: 1.5, CacheRead: 0.5},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3-VL-8B-Instruct": {
			ID:         "Qwen/Qwen3-VL-8B-Instruct",
			Name:       "Qwen3-VL-8B-Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.18, Output: 0.68, CacheRead: 0.18},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3.5-122B-A10B-FP8": {
			ID:         "Qwen/Qwen3.5-122B-A10B-FP8",
			Name:       "Qwen3.5 122B A10b Fp8",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3.5-2B-Lora": {
			ID:         "Qwen/Qwen3.5-2B-Lora",
			Name:       "Qwen3.5 2B Lora",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3.5-35B-A3B": {
			ID:         "Qwen/Qwen3.5-35B-A3B",
			Name:       "Qwen3.5 35B A3b",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3.5-35B-A3B-Lora": {
			ID:         "Qwen/Qwen3.5-35B-A3B-Lora",
			Name:       "Qwen3.5 35B A3B Lora",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3.5-397B-A17B": {
			ID:          "Qwen/Qwen3.5-397B-A17B",
			Name:        "Qwen3.5 397B A17b",
			Family:      "qwen",
			Reasoning:   true,
			ToolCall:    true,
			OpenWeights: true,
			ReleaseDate: "2026-02-16",
			Modalities:  &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.6, Output: 3.6, CacheRead: 0.35},
			Limit:       &Limit{Context: 262144, Output: 130000},
		},
		"Qwen/Qwen3.5-9B": {
			ID:               "Qwen/Qwen3.5-9B",
			Name:             "Qwen3.5 9B FP8",
			Family:           "qwen",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			OpenWeights:      true,
			ReleaseDate:      "2026-03-03",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.17, Output: 0.25, CacheRead: 0.17},
			Limit:            &Limit{Context: 262144, Output: 65536},
		},
		"Qwen/Qwen3.5-9B-FP8": {
			ID:         "Qwen/Qwen3.5-9B-FP8",
			Name:       "Qwen3.5 9B Fp8",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3.6-35B-A3B-FP8": {
			ID:         "Qwen/Qwen3.6-35B-A3B-FP8",
			Name:       "Qwen3.6 35B A3b Fp8",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3.6-35B-A3B-Lora": {
			ID:         "Qwen/Qwen3.6-35B-A3B-Lora",
			Name:       "Qwen3.6 35B A3B Lora",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"Qwen/Qwen3.6-Plus": {
			ID:          "Qwen/Qwen3.6-Plus",
			Name:        "Qwen3.6 Plus",
			Family:      "qwen",
			Reasoning:   true,
			ToolCall:    true,
			OpenWeights: true,
			ReleaseDate: "2026-04-30",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.5, Output: 3, CacheRead: 0.5},
			Limit:       &Limit{Context: 1000000, Output: 500000},
		},
		"Qwen/Qwen3.7-Max": {
			ID:          "Qwen/Qwen3.7-Max",
			Name:        "Qwen3.7 Max",
			Family:      "qwen",
			ToolCall:    true,
			ReleaseDate: "2026-05-21",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 1.25, Output: 3.75, CacheRead: 0.125},
			Limit:       &Limit{Context: 1000000, Output: 500000},
		},
		"Qwen/Qwen3.7-Plus": {
			ID:         "Qwen/Qwen3.7-Plus",
			Name:       "Qwen3.7 Plus",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.32, Output: 1.28, CacheRead: 0.32},
			Limit:      &Limit{Context: 1000000, Output: 0},
		},
		"agentica-org/DeepCoder-14B-Preview": {
			ID:         "agentica-org/DeepCoder-14B-Preview",
			Name:       "Deepcoder 14B Preview",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"allenai/Molmo-7B-D-0924": {
			ID:         "allenai/Molmo-7B-D-0924",
			Name:       "Molmo 7B D 0924",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 4096, Output: 0},
		},
		"arcee-ai/trinity-mini": {
			ID:         "arcee-ai/trinity-mini",
			Name:       "Trinity Mini",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.045, Output: 0.15, CacheRead: 0.045},
			Limit:      &Limit{Context: 128000, Output: 0},
		},
		"arize-ai/qwen-2-1.5b-instruct": {
			ID:         "arize-ai/qwen-2-1.5b-instruct",
			Name:       "Arize AI Qwen 2 1.5B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.1, Output: 0.1, CacheRead: 0.1},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"deepcogito/cogito-v1-preview-llama-70B": {
			ID:         "deepcogito/cogito-v1-preview-llama-70B",
			Name:       "Cogito V1 Preview Llama 70B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"deepcogito/cogito-v1-preview-llama-70B-Turbo": {
			ID:         "deepcogito/cogito-v1-preview-llama-70B-Turbo",
			Name:       "Cogito V1 Preview Llama 70B Turbo",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"deepcogito/cogito-v1-preview-llama-8B": {
			ID:         "deepcogito/cogito-v1-preview-llama-8B",
			Name:       "Cogito V1 Preview Llama 8B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"deepcogito/cogito-v1-preview-qwen-14B": {
			ID:         "deepcogito/cogito-v1-preview-qwen-14B",
			Name:       "Cogito V1 Preview Qwen 14B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"deepcogito/cogito-v1-preview-qwen-32B": {
			ID:         "deepcogito/cogito-v1-preview-qwen-32B",
			Name:       "Cogito V1 Preview Qwen 32B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"deepcogito/cogito-v2-1-671b": {
			ID:          "deepcogito/cogito-v2-1-671b",
			Name:        "Cogito v2.1 671B",
			Family:      "cogito",
			Reasoning:   true,
			ReleaseDate: "2025-11-13",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 1.25, Output: 1.25, CacheRead: 1.25},
			Limit:       &Limit{Context: 163840, Output: 163840},
		},
		"deepseek-ai/DeepSeek-OCR-2": {
			ID:         "deepseek-ai/DeepSeek-OCR-2",
			Name:       "Deepseek OCR 2",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 8192, Output: 0},
		},
		"deepseek-ai/DeepSeek-R1-0528": {
			ID:         "deepseek-ai/DeepSeek-R1-0528",
			Name:       "DeepSeek R1 0528 NVFP4",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 3, Output: 7, CacheRead: 3},
			Limit:      &Limit{Context: 163840, Output: 0},
		},
		"deepseek-ai/DeepSeek-R1-Distill-Llama-70B": {
			ID:         "deepseek-ai/DeepSeek-R1-Distill-Llama-70B",
			Name:       "DeepSeek R1 Distill Llama 70B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 2, Output: 2, CacheRead: 2},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B": {
			ID:         "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B",
			Name:       "DeepSeek R1 Distill Qwen 1.5B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.18, Output: 0.18, CacheRead: 0.18},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"deepseek-ai/DeepSeek-R1-Distill-Qwen-14B": {
			ID:         "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B",
			Name:       "DeepSeek R1 Distill Qwen 14B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 1.6, Output: 1.6, CacheRead: 1.6},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"deepseek-ai/DeepSeek-R1-Distill-Qwen-7B": {
			ID:         "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
			Name:       "DeepSeek R1 Distill Qwen 7B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"deepseek-ai/DeepSeek-V3.1": {
			ID:         "deepseek-ai/DeepSeek-V3.1",
			Name:       "Deepseek V3.1 NVFP4",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.6, Output: 1.7, CacheRead: 0.6},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"deepseek-ai/DeepSeek-V4-Pro": {
			ID:               "deepseek-ai/DeepSeek-V4-Pro",
			Name:             "Deepseek V4 Pro",
			Family:           "deepseek",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			OpenWeights:      true,
			ReleaseDate:      "2026-04-24",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.74, Output: 3.48, CacheRead: 0.2},
			Limit:            &Limit{Context: 512000, Output: 384000},
		},
		"deepseek-ai/deepseek-coder-33b-instruct": {
			ID:         "deepseek-ai/deepseek-coder-33b-instruct",
			Name:       "Deepseek Coder 33B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.8, Output: 0.8, CacheRead: 0.8},
			Limit:      &Limit{Context: 16384, Output: 0},
		},
		"google/gemma-2-27b-it": {
			ID:         "google/gemma-2-27b-it",
			Name:       "Gemma-2 Instruct (27B)",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.8, Output: 0.8, CacheRead: 0.8},
			Limit:      &Limit{Context: 8192, Output: 0},
		},
		"google/gemma-2-9b-it": {
			ID:         "google/gemma-2-9b-it",
			Name:       "Gemma 2 9B It",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 8192, Output: 0},
		},
		"google/gemma-2b-it": {
			ID:         "google/gemma-2b-it",
			Name:       "Gemma 2B It",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 8192, Output: 0},
		},
		"google/gemma-3-1b-it": {
			ID:         "google/gemma-3-1b-it",
			Name:       "Gemma 3 1b it",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"google/gemma-3-270m-it": {
			ID:         "google/gemma-3-270m-it",
			Name:       "Gemma 3 270M It",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"google/gemma-3-270m-it-lora": {
			ID:         "google/gemma-3-270m-it-lora",
			Name:       "Gemma 3 270M It Lora",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"google/gemma-3-27b-it": {
			ID:         "google/gemma-3-27b-it",
			Name:       "Gemma 3 27B It",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 65536, Output: 0},
		},
		"google/gemma-3-27b-it-lora": {
			ID:         "google/gemma-3-27b-it-lora",
			Name:       "Gemma 3 27B It Lora",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
		},
		"google/gemma-3-4b-it": {
			ID:         "google/gemma-3-4b-it",
			Name:       "Gemma 3 4b it",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 65536, Output: 0},
		},
		"google/gemma-3n-E4B-it": {
			ID:               "google/gemma-3n-E4B-it",
			Name:             "Gemma 3N E4B Instruct",
			Family:           "gemma",
			StructuredOutput: true,
			OpenWeights:      true,
			ReleaseDate:      "2025-05-20",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.06, Output: 0.12, CacheRead: 0.06},
			Limit:            &Limit{Context: 32768, Output: 32768},
		},
		"google/gemma-4-12B-it": {
			ID:         "google/gemma-4-12B-it",
			Name:       "Gemma 4 12B It",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"google/gemma-4-26B-A4B-it": {
			ID:         "google/gemma-4-26B-A4B-it",
			Name:       "Gemma 4 26B A4b It",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"google/gemma-4-31B-it": {
			ID:               "google/gemma-4-31B-it",
			Name:             "Gemma 4 31B-it FP8",
			Family:           "gemma",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			OpenWeights:      true,
			Knowledge:        "2025-01",
			ReleaseDate:      "2026-04-07",
			Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.39, Output: 0.97, CacheRead: 0.39},
			Limit:            &Limit{Context: 262144, Output: 131072},
		},
		"google/gemma-4-31B-it-lora": {
			ID:         "google/gemma-4-31B-it-lora",
			Name:       "Gemma 4 31B It Lora",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"google/gemma-4-E2B-it": {
			ID:         "google/gemma-4-E2B-it",
			Name:       "Gemma 4 E2B-it",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"google/gemma-4-E4B-it": {
			ID:         "google/gemma-4-E4B-it",
			Name:       "Gemma 4 E4B-it",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"google/medgemma-27b-text-it": {
			ID:         "google/medgemma-27b-text-it",
			Name:       "Medgemma 27B Text It",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"meta-llama/Llama-2-7b-chat-hf": {
			ID:         "meta-llama/Llama-2-7b-chat-hf",
			Name:       "meta-llama/Llama-2-7b-chat-hf",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 4096, Output: 0},
		},
		"meta-llama/Llama-3-8b-chat-hf": {
			ID:         "meta-llama/Llama-3-8b-chat-hf",
			Name:       "Meta Llama 3 8B Instruct Reference",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.2, Output: 0.2, CacheRead: 0.2},
			Limit:      &Limit{Context: 8192, Output: 0},
		},
		"meta-llama/Llama-3.1-405B": {
			ID:         "meta-llama/Llama-3.1-405B",
			Name:       "Llama 3.1 405B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"meta-llama/Llama-3.1-405B-Instruct": {
			ID:         "meta-llama/Llama-3.1-405B-Instruct",
			Name:       "Meta Llama 3.1 405B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 3.5, Output: 3.5, CacheRead: 3.5},
			Limit:      &Limit{Context: 4096, Output: 0},
		},
		"meta-llama/Llama-3.2-1B": {
			ID:         "meta-llama/Llama-3.2-1B",
			Name:       "Llama 3.2 1B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"meta-llama/Llama-3.2-1B-Instruct": {
			ID:         "meta-llama/Llama-3.2-1B-Instruct",
			Name:       "Meta Llama 3.2 1B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.06, Output: 0.06, CacheRead: 0.06},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"meta-llama/Llama-3.2-3B-Instruct": {
			ID:         "meta-llama/Llama-3.2-3B-Instruct",
			Name:       "Meta Llama 3.2 3B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.06, Output: 0.06, CacheRead: 0.06},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"meta-llama/Llama-3.3-70B-Instruct": {
			ID:         "meta-llama/Llama-3.3-70B-Instruct",
			Name:       "Meta Llama 3.3 70B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"meta-llama/Llama-3.3-70B-Instruct-FP8-Lora": {
			ID:         "meta-llama/Llama-3.3-70B-Instruct-FP8-Lora",
			Name:       "Llama 3.3 70B Instruct FP8 Lora",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"meta-llama/Llama-3.3-70B-Instruct-Turbo": {
			ID:          "meta-llama/Llama-3.3-70B-Instruct-Turbo",
			Name:        "Meta Llama 3.3 70B Instruct Turbo",
			Family:      "llama",
			ToolCall:    true,
			OpenWeights: true,
			Knowledge:   "2023-12",
			ReleaseDate: "2024-12-06",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 1.04, Output: 1.04, CacheRead: 1.04},
			Limit:       &Limit{Context: 131072, Output: 131072},
		},
		"meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP4": {
			ID:         "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP4",
			Name:       "Llama 4 Maverick 17B 128E Instruct Nvfp4",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 1048576, Output: 0},
		},
		"meta-llama/Llama-4-Scout-17B-16E": {
			ID:         "meta-llama/Llama-4-Scout-17B-16E",
			Name:       "Llama 4 Scout (17Bx16E)",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"meta-llama/Llama-4-Scout-17B-16E-Instruct": {
			ID:         "meta-llama/Llama-4-Scout-17B-16E-Instruct",
			Name:       "Llama 4 Scout Instruct (17Bx16E)",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.18, Output: 0.59, CacheRead: 0.18},
			Limit:      &Limit{Context: 1048576, Output: 0},
		},
		"meta-llama/Llama-4-Scout-17B-16E-Instruct-FP8-Lora": {
			ID:         "meta-llama/Llama-4-Scout-17B-16E-Instruct-FP8-Lora",
			Name:       "Llama 4 Scout 17B 16E Instruct Fp8 Lora",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 10485760, Output: 0},
		},
		"meta-llama/Meta-Llama-3-70B-Instruct-Turbo": {
			ID:         "meta-llama/Meta-Llama-3-70B-Instruct-Turbo",
			Name:       "Meta Llama 3 70B Instruct Turbo",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.88, Output: 0.88, CacheRead: 0.88},
			Limit:      &Limit{Context: 8192, Output: 0},
		},
		"meta-llama/Meta-Llama-3-8B-Instruct": {
			ID:         "meta-llama/Meta-Llama-3-8B-Instruct",
			Name:       "Meta Llama 3 8B Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.2, Output: 0.2, CacheRead: 0.2},
			Limit:      &Limit{Context: 8192, Output: 0},
		},
		"meta-llama/Meta-Llama-3.1-70B": {
			ID:         "meta-llama/Meta-Llama-3.1-70B",
			Name:       "Llama 3.1 70B",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo": {
			ID:         "meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",
			Name:       "Meta Llama 3.1 70B Instruct Turbo",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.88, Output: 0.88, CacheRead: 0.88},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo": {
			ID:         "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo",
			Name:       "Meta Llama 3.1 8B Instruct Turbo",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.18, Output: 0.18, CacheRead: 0.18},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"mistralai/Devstral-Small-2505": {
			ID:         "mistralai/Devstral-Small-2505",
			Name:       "Devstral Small 2505",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"mistralai/Magistral-Small-2506": {
			ID:         "mistralai/Magistral-Small-2506",
			Name:       "Magistral Small 2506",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 40960, Output: 0},
		},
		"mistralai/Ministral-3-14B-Instruct-2512": {
			ID:         "mistralai/Ministral-3-14B-Instruct-2512",
			Name:       "Ministral 3 14B Instruct 2512",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.2, Output: 0.2, CacheRead: 0.2},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"mistralai/Mistral-7B-Instruct-v0.1": {
			ID:         "mistralai/Mistral-7B-Instruct-v0.1",
			Name:       "Mistral (7B) Instruct v0.1",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.2, Output: 0.2, CacheRead: 0.2},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"mistralai/Mistral-7B-Instruct-v0.3": {
			ID:         "mistralai/Mistral-7B-Instruct-v0.3",
			Name:       "Mistral (7B) Instruct v0.3",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.2, Output: 0.2, CacheRead: 0.2},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"mistralai/Mistral-7B-v0.1": {
			ID:         "mistralai/Mistral-7B-v0.1",
			Name:       "Mistral 7B v0.1",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"mistralai/Mistral-Small-24B-Instruct-2501": {
			ID:         "mistralai/Mistral-Small-24B-Instruct-2501",
			Name:       "Mistral Small (24B) Instruct 25.01",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.1, Output: 0.3, CacheRead: 0.1},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"mistralai/Mixtral-8x22B-Instruct-v0.1": {
			ID:         "mistralai/Mixtral-8x22B-Instruct-v0.1",
			Name:       "Mixtral 8X22b Instruct V0.1",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 65536, Output: 0},
		},
		"mistralai/Mixtral-8x7B-Instruct-v0.1": {
			ID:         "mistralai/Mixtral-8x7B-Instruct-v0.1",
			Name:       "Mixtral-8x7B Instruct v0.1",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.6, Output: 0.6, CacheRead: 0.6},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"mistralai/Mixtral-8x7B-Instruct-v0.1-FP8-Lora": {
			ID:         "mistralai/Mixtral-8x7B-Instruct-v0.1-FP8-Lora",
			Name:       "Mixtral 8x7B Instruct V0.1 FP8 Lora",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"moonshotai/Kimi-K2.5-fp4": {
			ID:         "moonshotai/Kimi-K2.5-fp4",
			Name:       "Kimi K2.5 Fp4",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.5, Output: 2.8, CacheRead: 0.5},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"moonshotai/Kimi-K2.6": {
			ID:               "moonshotai/Kimi-K2.6",
			Name:             "Kimi K2.6 Fp4",
			Family:           "kimi-k2",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			OpenWeights:      true,
			Knowledge:        "2025-01",
			ReleaseDate:      "2026-04-21",
			Modalities:       &Modalities{Input: []string{"text", "image", "video"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.2, Output: 4.5, CacheRead: 0.2},
			Limit:            &Limit{Context: 262144, Output: 131000},
		},
		"moonshotai/Kimi-K2.7-Code": {
			ID:               "moonshotai/Kimi-K2.7-Code",
			Name:             "Kimi K2.7 Code",
			Family:           "kimi-k2",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			OpenWeights:      true,
			ReleaseDate:      "2026-06-14",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.95, Output: 4, CacheRead: 0.19},
			Limit:            &Limit{Context: 262144, Output: 131072},
		},
		"nim/meta/llama-3.1-70b-instruct": {
			ID:         "nim/meta/llama-3.1-70b-instruct",
			Name:       "nim/meta/llama-3.1-70b-instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 16384, Output: 0},
		},
		"nim/meta/llama-3.1-8b-instruct": {
			ID:         "nim/meta/llama-3.1-8b-instruct",
			Name:       "nim/meta/llama-3.1-8b-instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 16384, Output: 0},
		},
		"nim/meta/llama-3.2-11b-vision-instruct": {
			ID:         "nim/meta/llama-3.2-11b-vision-instruct",
			Name:       "nim/meta/llama-3.2-11b-vision-instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 16384, Output: 0},
		},
		"nim/meta/llama-3.2-90b-vision-instruct": {
			ID:         "nim/meta/llama-3.2-90b-vision-instruct",
			Name:       "nim/meta/llama-3.2-90b-vision-instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 16384, Output: 0},
		},
		"nim/meta/llama-3.3-70b-instruct": {
			ID:         "nim/meta/llama-3.3-70b-instruct",
			Name:       "nim/meta/llama-3.3-70b-instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 16384, Output: 0},
		},
		"nim/mistralai/mixtral-8x22b-instruct-v01": {
			ID:         "nim/mistralai/mixtral-8x22b-instruct-v01",
			Name:       "nim/mistralai/mixtral-8x22b-instruct-v01",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 16384, Output: 0},
		},
		"nim/mistralai/mixtral-8x7b-instruct-v01": {
			ID:         "nim/mistralai/mixtral-8x7b-instruct-v01",
			Name:       "nim/mistralai/mixtral-8x7b-instruct-v01",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 16384, Output: 0},
		},
		"nim/nv-mistralai/mistral-nemo-12b-instruct": {
			ID:         "nim/nv-mistralai/mistral-nemo-12b-instruct",
			Name:       "nim/nv-mistralai/mistral-nemo-12b-instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 16384, Output: 0},
		},
		"nim/nvidia/llama-3.1-nemotron-70b-instruct": {
			ID:         "nim/nvidia/llama-3.1-nemotron-70b-instruct",
			Name:       "nim/nvidia/llama-3.1-nemotron-70b-instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 16384, Output: 0},
		},
		"nim/nvidia/llama-3.3-nemotron-super-49b-v1": {
			ID:         "nim/nvidia/llama-3.3-nemotron-super-49b-v1",
			Name:       "nim/nvidia/llama-3.3-nemotron-super-49b-v1",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 16384, Output: 0},
		},
		"nvidia/Llama-3.1-Nemotron-70B-Instruct-HF": {
			ID:         "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF",
			Name:       "Llama 3.1 Nemotron 70B Instruct HF",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.88, Output: 0.88, CacheRead: 0.88},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16": {
			ID:         "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16",
			Name:       "Nvidia Nemotron 3 Nano 30B A3b Bf16",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-BF16": {
			ID:         "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-BF16",
			Name:       "Nvidia Nemotron 3 Super 120B A12b Bf16",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8": {
			ID:         "nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8",
			Name:       "Nvidia Nemotron 3 Super 120B A12b Fp8",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"nvidia/NVIDIA-Nemotron-Nano-9B-v2": {
			ID:         "nvidia/NVIDIA-Nemotron-Nano-9B-v2",
			Name:       "Nvidia Nemotron Nano 9B V2",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.06, Output: 0.25, CacheRead: 0.06},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"nvidia/nemotron-3-nano-omni-30b-a3b-reasoning-fp8": {
			ID:         "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning-fp8",
			Name:       "Nemotron 3 Nano Omni 30B A3b Reasoning Fp8",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"nvidia/nemotron-3-ultra-550b-a55b": {
			ID:               "nvidia/nemotron-3-ultra-550b-a55b",
			Name:             "NVIDIA Nemotron 3 Ultra 550B A55B NVFP4",
			Family:           "nemotron",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			OpenWeights:      true,
			ReleaseDate:      "2026-06-04",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.6, Output: 3.6, CacheRead: 0.2},
			Limit:            &Limit{Context: 512288, Output: 512300},
		},
		"openai/gpt-oss-120b": {
			ID:          "openai/gpt-oss-120b",
			Name:        "OpenAI GPT-OSS 120B",
			Family:      "gpt-oss",
			Reasoning:   true,
			ToolCall:    true,
			OpenWeights: true,
			Knowledge:   "2025-08",
			ReleaseDate: "2025-08-05",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.15, Output: 0.6, CacheRead: 0.15},
			Limit:       &Limit{Context: 131072, Output: 131072},
		},
		"openai/gpt-oss-20b": {
			ID:               "openai/gpt-oss-20b",
			Name:             "OpenAI GPT-OSS 20B",
			Family:           "gpt-oss",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			OpenWeights:      true,
			ReleaseDate:      "2025-08-05",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 0.05, Output: 0.2, CacheRead: 0.05},
			Limit:            &Limit{Context: 131072, Output: 131072},
		},
		"pearl-ai/gemma-4-31b-it": {
			ID:          "pearl-ai/gemma-4-31b-it",
			Name:        "Pearl-ai Gemma-4-31B-it-pearl",
			Family:      "gemma",
			Reasoning:   true,
			ReleaseDate: "2026-04-07",
			Modalities:  &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:        &Cost{Input: 0.28, Output: 0.86, CacheRead: 0.28},
			Limit:       &Limit{Context: 262144, Output: 32000},
		},
		"sarvamai/sarvam-m": {
			ID:         "sarvamai/sarvam-m",
			Name:       "Sarvam M",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"thinkingmachines/Inkling": {
			ID:         "thinkingmachines/Inkling",
			Name:       "Inkling FP4",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 1, Output: 4.05, CacheRead: 0.17},
			Limit:      &Limit{Context: 524288, Output: 0},
		},
		"togethercomputer/EssentialAI-RNJ-1-Instruct": {
			ID:         "togethercomputer/EssentialAI-RNJ-1-Instruct",
			Name:       "EssentialAI Rnj-1 Instruct",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 32768, Output: 0},
		},
		"togethercomputer/meta-llama-3.1-8B-Instruct-AWQ-INT4": {
			ID:         "togethercomputer/meta-llama-3.1-8B-Instruct-AWQ-INT4",
			Name:       "Meta Llama 3.1 8B Instruct Awq Int4",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"zai-org/GLM-4.5-Air-FP8": {
			ID:         "zai-org/GLM-4.5-Air-FP8",
			Name:       "Glm 4.5 Air Fp8",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.2, Output: 1.1, CacheRead: 0.2},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
		"zai-org/GLM-4.5V": {
			ID:         "zai-org/GLM-4.5V",
			Name:       "GLM 4.5V",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 65536, Output: 0},
		},
		"zai-org/GLM-4.6": {
			ID:         "zai-org/GLM-4.6",
			Name:       "GLM 4.6 Fp8",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.6, Output: 2.2, CacheRead: 0.6},
			Limit:      &Limit{Context: 202752, Output: 0},
		},
		"zai-org/GLM-4.7": {
			ID:         "zai-org/GLM-4.7",
			Name:       "GLM 4.7 FP8",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0.45, Output: 2, CacheRead: 0.45},
			Limit:      &Limit{Context: 202752, Output: 0},
		},
		"zai-org/GLM-4.7-FP8": {
			ID:         "zai-org/GLM-4.7-FP8",
			Name:       "Glm 4.7 Fp8",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 202752, Output: 0},
		},
		"zai-org/GLM-4.7-fp4": {
			ID:         "zai-org/GLM-4.7-fp4",
			Name:       "GLM 4.7 FP4",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 202752, Output: 0},
		},
		"zai-org/GLM-5": {
			ID:               "zai-org/GLM-5",
			Name:             "GLM 5 Fp4",
			Family:           "glm",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			OpenWeights:      true,
			ReleaseDate:      "2026-02-11",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1, Output: 3.2, CacheRead: 1},
			Limit:            &Limit{Context: 202752, Output: 131072},
		},
		"zai-org/GLM-5-FP4": {
			ID:         "zai-org/GLM-5-FP4",
			Name:       "GLM 5 Fp4",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 202752, Output: 0},
		},
		"zai-org/GLM-5.1": {
			ID:               "zai-org/GLM-5.1",
			Name:             "GLM 5.1 FP4",
			Family:           "glm",
			Reasoning:        true,
			ToolCall:         true,
			StructuredOutput: true,
			OpenWeights:      true,
			Knowledge:        "2025-11",
			ReleaseDate:      "2026-04-07",
			Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:             &Cost{Input: 1.4, Output: 4.4, CacheRead: 0.26},
			Limit:            &Limit{Context: 202752, Output: 131072},
		},
		"zai-org/GLM-5.2": {
			ID:         "zai-org/GLM-5.2",
			Name:       "GLM 5.2",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 1.4, Output: 4.4, CacheRead: 0.26},
			Limit:      &Limit{Context: 262144, Output: 0},
		},
		"zai-org/GLM-OCR": {
			ID:         "zai-org/GLM-OCR",
			Name:       "GLM OCR",
			Modalities: &Modalities{Input: []string{"text"}, Output: []string{"text"}},
			Cost:       &Cost{Input: 0, Output: 0, CacheRead: 0},
			Limit:      &Limit{Context: 131072, Output: 0},
		},
	},
}
