// Code generated from models.dev catalog snapshot — manually curated.
// To extend: add provider/model entries below. Each entry must reference
// a real, manually-tested model. Run `go test ./internal/registry/...` after.
//
// Inclusion policy: every model with release_date >= 2025-11 from each
// curated provider is shipped. Providers with no recent qualifying models
// (e.g. cohere, groq) fall back to their top 5 most-recent tool-call models
// so the catalog is never empty for any provider in the allow-list.
package registry

// curatedProviders is the static allow-list backing registry.Global().
// Replaces the previous //go:embed models.json approach with a hand-
// maintained Go literal so additions go through code review.
var curatedProviders = []Provider{
	atlasCloudProvider,
	deepSeekProvider,
	engyProvider,
	novitaProvider,
	theGridProvider,
	theseanProvider,
	togetherProvider,
	{ // anthropic — Anthropic
		ID:   "anthropic",
		Name: "Anthropic",
		Doc:  "https://docs.anthropic.com/en/docs/about-claude/models",
		Models: map[string]Model{
			"claude-sonnet-5": {
				ID:               "claude-sonnet-5",
				Name:             "Claude Sonnet 5",
				Family:           "claude-sonnet",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				ReleaseDate:      "2026-06-30",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:      2,
					Output:     10,
					CacheRead:  0.2,
					CacheWrite: 2.5,
				},
				Limit: &Limit{
					Context: 1000000,
					Output:  128000,
				},
			},
			"claude-opus-4-7": {
				ID:          "claude-opus-4-7",
				Name:        "Claude Opus 4.7",
				Family:      "claude-opus",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2026-01-31",
				ReleaseDate: "2026-04-16",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  5,
					Output: 25,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  64000,
				},
			},
			"claude-sonnet-4-6": {
				ID:          "claude-sonnet-4-6",
				Name:        "Claude Sonnet 4.6",
				Family:      "claude-sonnet",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08",
				ReleaseDate: "2026-02-17",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  3,
					Output: 15,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  64000,
				},
			},
			"claude-sonnet-4-5": {
				ID:          "claude-sonnet-4-5",
				Name:        "Claude Sonnet 4.5 (latest)",
				Family:      "claude-sonnet",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-07-31",
				ReleaseDate: "2025-09-29",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  3,
					Output: 15,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  64000,
				},
			},
			"claude-sonnet-4-0": {
				ID:          "claude-sonnet-4-0",
				Name:        "Claude Sonnet 4",
				Family:      "claude-sonnet",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-03-31",
				ReleaseDate: "2025-05-22",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  3,
					Output: 15,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  16000,
				},
			},
			"claude-3-5-haiku-latest": {
				ID:          "claude-3-5-haiku-latest",
				Name:        "Claude Haiku 3.5 (latest)",
				Family:      "claude-haiku",
				ToolCall:    true,
				Knowledge:   "2024-07-31",
				ReleaseDate: "2024-10-22",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.8,
					Output: 4,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  8192,
				},
			},
			"claude-3-5-haiku-20241022": {
				ID:          "claude-3-5-haiku-20241022",
				Name:        "Claude Haiku 3.5",
				Family:      "claude-haiku",
				ToolCall:    true,
				Knowledge:   "2024-07-31",
				ReleaseDate: "2024-10-22",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.8,
					Output: 4,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  8192,
				},
			},
			"claude-opus-4-6": {
				ID:          "claude-opus-4-6",
				Name:        "Claude Opus 4.6",
				Family:      "claude-opus",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-05",
				ReleaseDate: "2026-02-05",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  5,
					Output: 25,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  128000,
				},
			},
			"claude-opus-4-5": {
				ID:          "claude-opus-4-5",
				Name:        "Claude Opus 4.5 (latest)",
				Family:      "claude-opus",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-03-31",
				ReleaseDate: "2025-11-24",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  5,
					Output: 25,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  64000,
				},
			},
			"claude-opus-4-5-20251101": {
				ID:          "claude-opus-4-5-20251101",
				Name:        "Claude Opus 4.5",
				Family:      "claude-opus",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-03-31",
				ReleaseDate: "2025-11-01",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  5,
					Output: 25,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  64000,
				},
			},
		},
	},
	// cohere removed — not in supported provider set
	{ // elevenlabs — ElevenLabs
		ID:   "elevenlabs",
		Name: "ElevenLabs",
		API:  "https://api.elevenlabs.io",
		Doc:  "https://elevenlabs.io/docs/api-reference/speech-to-text/convert",
		Models: map[string]Model{
			"scribe_v2": {
				ID:     "scribe_v2",
				Name:   "Scribe v2",
				Family: "scribe",
				Modalities: &Modalities{
					Input:  []string{"audio"},
					Output: []string{"text"},
				},
				Description: "Speech-to-text transcription model; direct API pricing is duration-based.",
			},
		},
	},
	{ // reve — Reve
		ID:   "reve",
		Name: "Reve",
		API:  "https://api.reve.com",
		Doc:  "https://api.reve.com/console/docs",
		Models: map[string]Model{
			"reve-image": {
				ID:     "reve-image",
				Name:   "Reve Image",
				Family: "reve-image",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"image"},
				},
				Description: "Default raster image model through the Reve v2 image create API.",
			},
		},
	},
	{ // quiver — Quiver AI
		ID:   "quiver",
		Name: "Quiver AI",
		API:  "https://api.quiver.ai",
		Doc:  "https://docs.quiver.ai/api-reference/introduction",
		Models: map[string]Model{
			"arrow-1.1": {
				ID:     "arrow-1.1",
				Name:   "Quiver Arrow 1.1",
				Family: "quiver-vector",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"image"},
				},
				Description: "Default SVG/vector image model through the Quiver AI text-to-svg API.",
			},
		},
	},
	{ // fireworks-ai — Fireworks AI
		ID:   "fireworks-ai",
		Name: "Fireworks AI",
		API:  "https://api.fireworks.ai/inference/v1/",
		Doc:  "https://fireworks.ai/docs/",
		Models: map[string]Model{
			"accounts/fireworks/models/minimax-m2p5": {
				ID:          "accounts/fireworks/models/minimax-m2p5",
				Name:        "MiniMax-M2.5",
				Family:      "minimax",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2026-02-12",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.3,
					Output: 1.2,
				},
				Limit: &Limit{
					Context: 196608,
					Output:  196608,
				},
			},
			"accounts/fireworks/models/glm-5": {
				ID:          "accounts/fireworks/models/glm-5",
				Name:        "GLM 5",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2026-02-11",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1,
					Output: 3.2,
				},
				Limit: &Limit{
					Context: 202752,
					Output:  131072,
				},
			},
			"accounts/fireworks/models/kimi-k2p5": {
				ID:          "accounts/fireworks/models/kimi-k2p5",
				Name:        "Kimi K2.5",
				Family:      "kimi-thinking",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-01-27",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 3,
				},
				Limit: &Limit{
					Context: 256000,
					Output:  256000,
				},
			},
			"accounts/fireworks/models/kimi-k2p7-code": {
				ID:          "accounts/fireworks/models/kimi-k2p7-code",
				Name:        "Kimi K2.7 Code",
				Family:      "kimi-k2",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2026-06-12",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:     0.95,
					Output:    4,
					CacheRead: 0.19,
				},
				Limit: &Limit{
					Context: 262000,
					Output:  262000,
				},
			},
			"accounts/fireworks/models/minimax-m2p1": {
				ID:          "accounts/fireworks/models/minimax-m2p1",
				Name:        "MiniMax-M2.1",
				Family:      "minimax",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2025-12-23",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.3,
					Output: 1.2,
				},
				Limit: &Limit{
					Context: 200000,
					Output:  200000,
				},
			},
			"accounts/fireworks/models/glm-4p7": {
				ID:          "accounts/fireworks/models/glm-4p7",
				Name:        "GLM 4.7",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2025-12-22",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 2.2,
				},
				Limit: &Limit{
					Context: 198000,
					Output:  198000,
				},
			},
			"accounts/fireworks/models/kimi-k2-thinking": {
				ID:          "accounts/fireworks/models/kimi-k2-thinking",
				Name:        "Kimi K2 Thinking",
				Family:      "kimi-thinking",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2025-11-06",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 2.5,
				},
				Limit: &Limit{
					Context: 256000,
					Output:  256000,
				},
			},
		},
	},
	{ // google — Google
		ID:   "google",
		Name: "Google",
		Doc:  "https://ai.google.dev/gemini-api/docs/pricing",
		Models: map[string]Model{
			"gemini-3.5-flash": {
				ID:          "gemini-3.5-flash",
				Name:        "Gemini 3.5 Flash",
				Family:      "gemini-flash",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-05-19",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video", "audio", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.5,
					Output: 9,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  65536,
				},
			},
			"gemini-3.1-flash-lite": {
				ID:          "gemini-3.1-flash-lite",
				Name:        "Gemini 3.1 Flash Lite",
				Family:      "gemini-flash-lite",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-05-07",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video", "audio", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.25,
					Output: 1.5,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  65536,
				},
			},
			"gemini-3.1-flash-lite-preview": {
				ID:          "gemini-3.1-flash-lite-preview",
				Name:        "Gemini 3.1 Flash Lite Preview",
				Family:      "gemini-flash-lite",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-03-03",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video", "audio", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.5,
					Output: 3,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  65536,
				},
			},
			"gemini-3.1-flash-image-preview": {
				ID:          "gemini-3.1-flash-image-preview",
				Name:        "Gemini 3.1 Flash Image (Preview)",
				Family:      "gemini-flash",
				Reasoning:   true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-02-26",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text", "image"},
				},
				Cost: &Cost{
					Input:  0.25,
					Output: 60,
				},
				Limit: &Limit{
					Context: 131072,
					Output:  32768,
				},
			},
			"gemini-3.1-pro-preview-customtools": {
				ID:          "gemini-3.1-pro-preview-customtools",
				Name:        "Gemini 3.1 Pro Preview Custom Tools",
				Family:      "gemini-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-02-19",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video", "audio", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2,
					Output: 12,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  65536,
				},
			},
			"gemini-3.1-pro-preview": {
				ID:          "gemini-3.1-pro-preview",
				Name:        "Gemini 3.1 Pro Preview",
				Family:      "gemini-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-02-19",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video", "audio", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2,
					Output: 12,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  65536,
				},
			},
			"gemini-3-flash-preview": {
				ID:          "gemini-3-flash-preview",
				Name:        "Gemini 3 Flash Preview",
				Family:      "gemini-flash",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2025-12-17",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video", "audio", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.5,
					Output: 3,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  65536,
				},
			},
			"gemini-3-pro-preview": {
				ID:          "gemini-3-pro-preview",
				Name:        "Gemini 3 Pro Preview",
				Family:      "gemini-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-01",
				ReleaseDate: "2025-11-18",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video", "audio", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2,
					Output: 12,
				},
				Limit: &Limit{
					Context: 1000000,
					Output:  64000,
				},
			},
			"gemini-2.5-flash": {
				ID:               "gemini-2.5-flash",
				Name:             "Gemini 2.5 Flash",
				Family:           "gemini-flash",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				Knowledge:        "2025-01",
				ReleaseDate:      "2025-03-20",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "audio", "video", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.3,
					Output: 2.5,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  65536,
				},
			},
		},
	},
	{ // groq — Groq
		ID:   "groq",
		Name: "Groq",
		Doc:  "https://console.groq.com/docs/models",
		Models: map[string]Model{
			"moonshotai/kimi-k2-instruct-0905": {
				ID:          "moonshotai/kimi-k2-instruct-0905",
				Name:        "Kimi K2 Instruct 0905",
				Family:      "kimi",
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-10",
				ReleaseDate: "2025-09-05",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1,
					Output: 3,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  16384,
				},
			},
			"openai/gpt-oss-20b": {
				ID:          "openai/gpt-oss-20b",
				Name:        "GPT OSS 20B",
				Family:      "gpt-oss",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2025-08-05",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.075,
					Output: 0.3,
				},
				Limit: &Limit{
					Context: 131072,
					Output:  65536,
				},
			},
			"openai/gpt-oss-120b": {
				ID:          "openai/gpt-oss-120b",
				Name:        "GPT OSS 120B",
				Family:      "gpt-oss",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2025-08-05",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.15,
					Output: 0.6,
				},
				Limit: &Limit{
					Context: 131072,
					Output:  65536,
				},
			},
			"moonshotai/kimi-k2-instruct": {
				ID:          "moonshotai/kimi-k2-instruct",
				Name:        "Kimi K2 Instruct",
				Family:      "kimi",
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-10",
				ReleaseDate: "2025-07-14",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1,
					Output: 3,
				},
				Limit: &Limit{
					Context: 131072,
					Output:  16384,
				},
				Status: "deprecated",
			},
		},
	},
	// mistral removed — no models from supported provider families
	{ // moonshotai — Moonshot AI
		ID:   "moonshotai",
		Name: "Moonshot AI",
		API:  "https://api.moonshot.ai/v1",
		Doc:  "https://platform.moonshot.ai/docs/api/chat",
		Models: map[string]Model{
			"kimi-k2.6": {
				ID:          "kimi-k2.6",
				Name:        "Kimi K2.6",
				Family:      "kimi",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-04-21",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.95,
					Output: 4,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  131000,
				},
			},
			"kimi-k2.7-code": {
				ID:               "kimi-k2.7-code",
				Name:             "Kimi K2.7 Code",
				Family:           "kimi-k2",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				OpenWeights:      true,
				Knowledge:        "2025-01",
				ReleaseDate:      "2026-06-12",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:     0.95,
					Output:    4,
					CacheRead: 0.19,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  262144,
				},
			},
			"kimi-k2.5": {
				ID:          "kimi-k2.5",
				Name:        "Kimi K2.5",
				Family:      "kimi",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-01",
				ReleaseDate: "2026-01",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 3,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  262144,
				},
			},
			"kimi-k2-thinking-turbo": {
				ID:          "kimi-k2-thinking-turbo",
				Name:        "Kimi K2 Thinking Turbo",
				Family:      "kimi-thinking",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-08",
				ReleaseDate: "2025-11-06",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.15,
					Output: 8,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  262144,
				},
			},
			"kimi-k2-thinking": {
				ID:          "kimi-k2-thinking",
				Name:        "Kimi K2 Thinking",
				Family:      "kimi-thinking",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-08",
				ReleaseDate: "2025-11-06",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 2.5,
				},
				Limit: &Limit{
					Context: 262144,
					Output:  262144,
				},
			},
		},
	},
	{ // openai — OpenAI
		ID:   "openai",
		Name: "OpenAI",
		Doc:  "https://platform.openai.com/docs/models",
		Models: map[string]Model{
			"gpt-5.5-pro": {
				ID:          "gpt-5.5-pro",
				Name:        "GPT-5.5 Pro",
				Family:      "gpt-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-04-23",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  30,
					Output: 180,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.5": {
				ID:          "gpt-5.5",
				Name:        "GPT-5.5",
				Family:      "gpt",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-04-23",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  5,
					Output: 30,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.4-pro": {
				ID:          "gpt-5.4-pro",
				Name:        "GPT-5.4 Pro",
				Family:      "gpt-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-03-05",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  30,
					Output: 180,
				},
				Limit: &Limit{
					Context: 1050000,
					Output:  128000,
				},
			},
			"gpt-5.4": {
				ID:          "gpt-5.4",
				Name:        "GPT-5.4",
				Family:      "gpt",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-03-05",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  2.5,
					Output: 15,
				},
				Limit: &Limit{
					Context: 1050000,
					Output:  128000,
				},
			},
			"gpt-5.4-mini": {
				ID:          "gpt-5.4-mini",
				Name:        "GPT-5.4 Mini",
				Family:      "gpt-mini",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-03-17",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.75,
					Output: 4.5,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.4-nano": {
				ID:          "gpt-5.4-nano",
				Name:        "GPT-5.4 Nano",
				Family:      "gpt-nano",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-03-17",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.2,
					Output: 1.25,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-4o-mini": {
				ID:               "gpt-4o-mini",
				Name:             "GPT-4o Mini",
				Family:           "gpt",
				ToolCall:         true,
				StructuredOutput: true,
				Knowledge:        "2023-10-01",
				ReleaseDate:      "2024-07-18",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.15,
					Output: 0.6,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  16384,
				},
			},
			"gpt-5.3-codex-spark": {
				ID:          "gpt-5.3-codex-spark",
				Name:        "GPT-5.3 Codex Spark",
				Family:      "gpt-codex-spark",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-02-05",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.75,
					Output: 14,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  32000,
				},
			},
			"gpt-5.3-codex": {
				ID:          "gpt-5.3-codex",
				Name:        "GPT-5.3 Codex",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2026-02-05",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.75,
					Output: 14,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.2-pro": {
				ID:          "gpt-5.2-pro",
				Name:        "GPT-5.2 Pro",
				Family:      "gpt-pro",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2025-12-11",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  21,
					Output: 168,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.2-codex": {
				ID:          "gpt-5.2-codex",
				Name:        "GPT-5.2 Codex",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2025-12-11",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "pdf"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.75,
					Output: 14,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.2-chat-latest": {
				ID:          "gpt-5.2-chat-latest",
				Name:        "GPT-5.2 Chat",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2025-12-11",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.75,
					Output: 14,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  16384,
				},
			},
			"gpt-5.2": {
				ID:          "gpt-5.2",
				Name:        "GPT-5.2",
				Family:      "gpt",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2025-08-31",
				ReleaseDate: "2025-12-11",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.75,
					Output: 14,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.1-codex-mini": {
				ID:          "gpt-5.1-codex-mini",
				Name:        "GPT-5.1 Codex mini",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.25,
					Output: 2,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.1-codex-max": {
				ID:          "gpt-5.1-codex-max",
				Name:        "GPT-5.1 Codex Max",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.25,
					Output: 10,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.1-codex": {
				ID:          "gpt-5.1-codex",
				Name:        "GPT-5.1 Codex",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.25,
					Output: 10,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
			"gpt-5.1-chat-latest": {
				ID:          "gpt-5.1-chat-latest",
				Name:        "GPT-5.1 Chat",
				Family:      "gpt-codex",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.25,
					Output: 10,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  16384,
				},
			},
			"gpt-5.1": {
				ID:          "gpt-5.1",
				Name:        "GPT-5.1",
				Family:      "gpt",
				Reasoning:   true,
				ToolCall:    true,
				Knowledge:   "2024-09-30",
				ReleaseDate: "2025-11-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1.25,
					Output: 10,
				},
				Limit: &Limit{
					Context: 400000,
					Output:  128000,
				},
			},
		},
	},
	{ // openrouter — OpenRouter
		ID:   "openrouter",
		Name: "OpenRouter",
		API:  "https://openrouter.ai/api/v1",
		Doc:  "https://openrouter.ai/models",
		Models: map[string]Model{
			"black-forest-labs/flux.2-klein-4b": {
				ID:          "black-forest-labs/flux.2-klein-4b",
				Name:        "FLUX.2 Klein 4B",
				Family:      "flux-image",
				OpenWeights: true,
				ReleaseDate: "2026-01-14",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"image"},
				},
				Limit: &Limit{
					Context: 41000,
				},
				Description: "Default open-weight raster image model. Optimized for fast high-throughput text-to-image and image-to-image generation; OpenRouter bills by output megapixel.",
			},
			"sourceful/riverflow-v2.5-fast": {
				ID:          "sourceful/riverflow-v2.5-fast",
				Name:        "Riverflow V2.5 Fast",
				Family:      "riverflow-image",
				Reasoning:   true,
				ReleaseDate: "2026-06-04",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"image"},
				},
				Limit: &Limit{
					Context: 33000,
				},
				Description: "Recent low-latency raster image model for production drafts and edits. Uses open diffusion components but is not a pure open-weight endpoint.",
			},
			"sourceful/riverflow-v2.5-pro": {
				ID:          "sourceful/riverflow-v2.5-pro",
				Name:        "Riverflow V2.5 Pro",
				Family:      "riverflow-image",
				Reasoning:   true,
				ReleaseDate: "2026-06-04",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"image"},
				},
				Limit: &Limit{
					Context: 33000,
				},
				Description: "Recent higher-control raster image model for quality-sensitive generation and editing. Supports 1K/2K/4K and multiple references through OpenRouter image configuration.",
			},
			"recraft/recraft-v4.1-vector": {
				ID:          "recraft/recraft-v4.1-vector",
				Name:        "Recraft V4.1 Vector",
				Family:      "recraft-vector",
				ReleaseDate: "2026-05-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"image"},
				},
				Limit: &Limit{
					Context: 66000,
				},
				Description: "Default vector/SVG image model for scalable icons, logos, illustrations, and canvas-ready graphics.",
			},
			"recraft/recraft-v4.1-pro-vector": {
				ID:          "recraft/recraft-v4.1-pro-vector",
				Name:        "Recraft V4.1 Pro Vector",
				Family:      "recraft-vector",
				ReleaseDate: "2026-05-13",
				Modalities: &Modalities{
					Input:  []string{"text", "image"},
					Output: []string{"image"},
				},
				Limit: &Limit{
					Context: 66000,
				},
				Description: "Premium vector/SVG image model for higher-resolution production graphics, icons, logos, and illustrations.",
			},
		},
	},
	{ // quantised — CrofAI Quantised
		ID:   "quantised",
		Name: "Quantised",
		API:  "https://crof.ai/v1",
		Doc:  "https://crof.ai/docs",
		Models: map[string]Model{
			"deepseek-v3.2": {
				ID:               "deepseek-v3.2",
				Name:             "Quantised DeepSeek V3.2 (Q6_K)",
				Family:           "deepseek",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
				Cost:             &Cost{Input: 0.18, Output: 0.35},
				Limit:            &Limit{Context: 163840, Output: 163840},
			},
			"deepseek-v4-pro": {
				ID:               "deepseek-v4-pro",
				Name:             "Quantised DeepSeek V4 Pro (Q8_0)",
				Family:           "deepseek-thinking",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
				Cost:             &Cost{Input: 0.35, Output: 0.80},
				Limit:            &Limit{Context: 1000000, Output: 131072},
			},
			"glm-4.7": {
				ID:               "glm-4.7",
				Name:             "Quantised GLM 4.7 (Q8_0)",
				Family:           "glm",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
				Cost:             &Cost{Input: 0.25, Output: 1.10},
				Limit:            &Limit{Context: 202752, Output: 202752},
			},
			"glm-4.7-flash": {
				ID:               "glm-4.7-flash",
				Name:             "Quantised GLM 4.7 Flash (FP8)",
				Family:           "glm-flash",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
				Cost:             &Cost{Input: 0.04, Output: 0.30},
				Limit:            &Limit{Context: 202752, Output: 131072},
			},
			"glm-5.1": {
				ID:               "glm-5.1",
				Name:             "Quantised GLM 5.1 (Q8_0)",
				Family:           "glm",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
				Cost:             &Cost{Input: 0.45, Output: 2.15},
				Limit:            &Limit{Context: 202752, Output: 202752},
			},
			"glm-5.2": {
				ID:               "glm-5.2",
				Name:             "Quantised GLM 5.2 (Q8_0)",
				Family:           "glm",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
				Cost:             &Cost{Input: 0.30, Output: 1.05},
				Limit:            &Limit{Context: 1000000, Output: 131072},
			},
			"kimi-k2.5": {
				ID:               "kimi-k2.5",
				Name:             "Quantised Kimi K2.5 (Q4_K_M)",
				Family:           "kimi-k2",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				Modalities:       &Modalities{Input: []string{"text", "image"}, Output: []string{"text"}},
				Cost:             &Cost{Input: 0.35, Output: 1.70},
				Limit:            &Limit{Context: 262144, Output: 262144},
			},
			"kimi-k2.5-lightning": {
				ID:               "kimi-k2.5-lightning",
				Name:             "Quantised Kimi K2.5 Lightning (530B-INT4)",
				Family:           "kimi-k2",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
				Cost:             &Cost{Input: 1.00, Output: 3.00},
				Limit:            &Limit{Context: 131072, Output: 32768},
			},
			"kimi-k2.6": {
				ID:               "kimi-k2.6",
				Name:             "Quantised Kimi K2.6 (INT4)",
				Family:           "kimi-k2",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
				Cost:             &Cost{Input: 0.50, Output: 1.99},
				Limit:            &Limit{Context: 262144, Output: 262144},
			},
			"kimi-k2.7-code": {
				ID:               "kimi-k2.7-code",
				Name:             "Quantised Kimi K2.7 Code (INT4)",
				Family:           "kimi-k2",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
				Cost:             &Cost{Input: 0.55, Output: 2.25},
				Limit:            &Limit{Context: 262144, Output: 262144},
			},
			"mimo-v2.5-pro": {
				ID:               "mimo-v2.5-pro",
				Name:             "Quantised MiMo V2.5 Pro (Q8_0)",
				Family:           "mimo",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
				Cost:             &Cost{Input: 0.40, Output: 0.80},
				Limit:            &Limit{Context: 1000000, Output: 131072},
			},
			"minimax-m2.5": {
				ID:               "minimax-m2.5",
				Name:             "Quantised MiniMax M2.5 (AWQ)",
				Family:           "minimax",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
				Cost:             &Cost{Input: 0.11, Output: 0.95},
				Limit:            &Limit{Context: 204800, Output: 131072},
			},
			"qwen3.5-9b": {
				ID:               "qwen3.5-9b",
				Name:             "Quantised Qwen3.5 9B (FP8)",
				Family:           "qwen",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				Modalities:       &Modalities{Input: []string{"text"}, Output: []string{"text"}},
				Cost:             &Cost{Input: 0.04, Output: 0.15},
				Limit:            &Limit{Context: 262144, Output: 262144},
			},
		},
	},
	{ // xiaomi — Xiaomi MiMo
		ID:   "xiaomi",
		Name: "Xiaomi MiMo",
		API:  "https://api.xiaomimimo.com/v1",
		Doc:  "https://platform.xiaomimimo.com/docs",
		Models: map[string]Model{
			"mimo-v2.5-pro-ultraspeed": {
				ID:               "mimo-v2.5-pro-ultraspeed",
				Name:             "MiMo-V2.5-Pro-Ultraspeed",
				Family:           "mimo",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				OpenWeights:      true,
				Knowledge:        "2024-12",
				ReleaseDate:      "2026-04-22",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:     1.305,
					Output:    2.61,
					CacheRead: 0.0108,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  131072,
				},
			},
			"mimo-v2.5-pro": {
				ID:               "mimo-v2.5-pro",
				Name:             "MiMo-V2.5-Pro",
				Family:           "mimo",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				OpenWeights:      true,
				Knowledge:        "2024-12",
				ReleaseDate:      "2026-04-22",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:     0.435,
					Output:    0.87,
					CacheRead: 0.0036,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  131072,
				},
			},
			"mimo-v2.5": {
				ID:          "mimo-v2.5",
				Name:        "MiMo-V2.5",
				Family:      "mimo",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2024-12",
				ReleaseDate: "2026-04-22",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "audio", "video"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:     0.14,
					Output:    0.28,
					CacheRead: 0.0028,
				},
				Limit: &Limit{
					Context: 1048576,
					Output:  131072,
				},
			},
		},
	},
	// togetherai, xai removed — not in supported provider set
	{ // zai — Z.AI
		ID:   "zai",
		Name: "Z.AI",
		API:  "https://api.z.ai/api/paas/v4",
		Doc:  "https://docs.z.ai/guides/overview/pricing",
		Models: map[string]Model{
			"glm-5": {
				ID:          "glm-5",
				Name:        "GLM-5",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2026-02-11",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1,
					Output: 3.2,
				},
				Limit: &Limit{
					Context: 204800,
					Output:  131072,
				},
			},
			"glm-4.7-flash": {
				ID:          "glm-4.7-flash",
				Name:        "GLM-4.7-Flash",
				Family:      "glm-flash",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2026-01-19",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 200000,
					Output:  131072,
				},
			},
			"glm-4.7": {
				ID:          "glm-4.7",
				Name:        "GLM-4.7",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2025-12-22",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 2.2,
				},
				Limit: &Limit{
					Context: 204800,
					Output:  131072,
				},
			},
			"glm-4.6v": {
				ID:          "glm-4.6v",
				Name:        "GLM-4.6V",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2025-12-08",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.3,
					Output: 0.9,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  32768,
				},
			},
		},
	},
	{ // zhipuai — Zhipu AI
		ID:   "zhipuai",
		Name: "Zhipu AI",
		API:  "https://open.bigmodel.cn/api/paas/v4",
		Doc:  "https://docs.z.ai/guides/overview/pricing",
		Models: map[string]Model{
			"glm-5.2": {
				ID:               "glm-5.2",
				Name:             "GLM-5.2",
				Family:           "glm",
				Reasoning:        true,
				ToolCall:         true,
				StructuredOutput: true,
				ReleaseDate:      "2026-06-13",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:     1.4,
					Output:    4.4,
					CacheRead: 0.26,
				},
				Limit: &Limit{
					Context: 1000000,
					Output:  131072,
				},
			},
			"glm-5": {
				ID:          "glm-5",
				Name:        "GLM-5",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				ReleaseDate: "2026-02-11",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  1,
					Output: 3.2,
				},
				Limit: &Limit{
					Context: 204800,
					Output:  131072,
				},
			},
			"glm-4.7-flash": {
				ID:          "glm-4.7-flash",
				Name:        "GLM-4.7-Flash",
				Family:      "glm-flash",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2026-01-19",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Limit: &Limit{
					Context: 200000,
					Output:  131072,
				},
			},
			"glm-4.7": {
				ID:          "glm-4.7",
				Name:        "GLM-4.7",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2025-12-22",
				Modalities: &Modalities{
					Input:  []string{"text"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.6,
					Output: 2.2,
				},
				Limit: &Limit{
					Context: 204800,
					Output:  131072,
				},
			},
			"glm-4.6v": {
				ID:          "glm-4.6v",
				Name:        "GLM-4.6V",
				Family:      "glm",
				Reasoning:   true,
				ToolCall:    true,
				OpenWeights: true,
				Knowledge:   "2025-04",
				ReleaseDate: "2025-12-08",
				Modalities: &Modalities{
					Input:  []string{"text", "image", "video"},
					Output: []string{"text"},
				},
				Cost: &Cost{
					Input:  0.3,
					Output: 0.9,
				},
				Limit: &Limit{
					Context: 128000,
					Output:  32768,
				},
			},
		},
	},
}
