apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: preview-usehivy
  namespace: ingress-public
spec:
  secretName: preview-usehivy-tls
  dnsNames:
    - preview.usehivy.com
    - "*.preview.usehivy.com"
    - api.usehivy.com
    - staging.api.usehivy.com
    - proxy.usehivy.com
    - staging.proxy.usehivy.com
    - mcp.usehivy.com
    - staging.mcp.usehivy.com
    - connections.usehivy.com
    - staging.connections.usehivy.com
    - usehivy.com
    - staging.usehivy.com
    - monitor.usehivy.com
    - telemetry.usehivy.com
  issuerRef:
    name: letsencrypt-production-vercel
    kind: ClusterIssuer
