apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  preview.override: |
    rewrite stop name exact preview.usehivy.com cilium-gateway-public.ingress-public.svc.cluster.local
    rewrite stop name regex (.*)\.preview\.usehivy\.com cilium-gateway-public.ingress-public.svc.cluster.local answer auto
