apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - qdrant.yaml
  - redis.yaml

configMapGenerator:
  - name: redis-backup-scripts
    files:
      - backup.sh=scripts/redis-backup.sh
      - upload.sh=scripts/redis-upload.sh
