package tasks

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/hibiken/asynq"
	"gorm.io/gorm"

	"github.com/usehivy/hivy/internal/cache"
	"github.com/usehivy/hivy/internal/model"
	"github.com/usehivy/hivy/internal/registry"
	"github.com/usehivy/hivy/internal/trigger/hivy"
)

func TestSessionNameHandlerHandleAutoGeneratesNameAndMarksTimestamp(t *testing.T) {
	db := connectTestDB(t)
	session := seedSessionNameFixture(t, db, "Investigate Linear issue HIVE-123 webhook retries")

	mock := hivy.NewMockCompletionClient()
	mock.SetFallback(hivy.CompletionResponse{
		Message: hivy.Message{
			Content: `{"name":"Investigate Linear HIVE-123 webhook retries"}`,
		},
	})

	handler := &SessionNameHandler{
		db:  db,
		reg: registry.Global(),
		loadNamingCredential: func(context.Context, *gorm.DB, *cache.Manager, *registry.Registry) (*sessionNameCredential, error) {
			return &sessionNameCredential{
				credential: &model.Credential{ProviderID: sessionNameProviderID},
				apiKey:     "sk-test",
				modelID:    "openai/gpt-4o-mini",
			}, nil
		},
		newCompletionClient: func(*model.Credential, string) hivy.CompletionClient {
			return mock
		},
	}

	task, _, err := NewSessionNameTask(session.ID)
	if err != nil {
		t.Fatalf("new task: %v", err)
	}
	if err := handler.Handle(context.Background(), task); err != nil {
		t.Fatalf("handle: %v", err)
	}

	var updated model.Session
	if err := db.Where("id = ?", session.ID).First(&updated).Error; err != nil {
		t.Fatalf("load session: %v", err)
	}

	if updated.Name != "investigate-linear-hive-123-webhook-retries" {
		t.Fatalf("session name=%q", updated.Name)
	}
	if updated.SessionNameAutoGeneratedAt == nil {
		t.Fatal("expected session_name_auto_generated_at to be set")
	}

	mock.AssertCallCount(t, 1)
	req := mock.LastRequest()
	if req.Model != "openai/gpt-4o-mini" {
		t.Fatalf("model=%q", req.Model)
	}
	if len(req.Messages) < 2 || req.Messages[1].Role != "user" {
		t.Fatalf("unexpected request messages=%+v", req.Messages)
	}
}

func TestSessionNameHandlerHandleSkipsWhenAlreadyAutoGenerated(t *testing.T) {
	db := connectTestDB(t)
	session := seedSessionNameFixture(t, db, "Investigate deploy failure")
	now := time.Now()
	if err := db.Model(&model.Session{}).
		Where("id = ?", session.ID).
		Update("session_name_auto_generated_at", now).Error; err != nil {
		t.Fatalf("mark autogenerated: %v", err)
	}

	handler := &SessionNameHandler{
		db: db,
		loadNamingCredential: func(context.Context, *gorm.DB, *cache.Manager, *registry.Registry) (*sessionNameCredential, error) {
			t.Fatal("loadNamingCredential should not be called")
			return nil, nil
		},
	}

	task := asynq.NewTask(TypeSessionName, mustMarshalSessionNamePayload(t, SessionNamePayload{SessionID: session.ID}))
	if err := handler.Handle(context.Background(), task); err != nil {
		t.Fatalf("handle: %v", err)
	}
}

func TestPickSessionNameCredentialPrefersOpenRouterSystemCredential(t *testing.T) {
	db := connectTestDB(t)

	openAI := model.Credential{
		Label:        "openai-system",
		BaseURL:      "https://api.openai.com/v1",
		AuthScheme:   "bearer",
		EncryptedKey: []byte("openai"),
		WrappedDEK:   []byte("openai"),
		ProviderID:   "openai",
	}
	if err := db.Create(&openAI).Error; err != nil {
		t.Fatalf("create openai credential: %v", err)
	}

	openRouter := model.Credential{
		Label:        "openrouter-system",
		BaseURL:      "https://openrouter.ai/api/v1",
		AuthScheme:   "bearer",
		EncryptedKey: []byte("openrouter"),
		WrappedDEK:   []byte("openrouter"),
		ProviderID:   sessionNameProviderID,
	}
	if err := db.Create(&openRouter).Error; err != nil {
		t.Fatalf("create openrouter credential: %v", err)
	}
	t.Cleanup(func() {
		db.Where("id IN ?", []uuid.UUID{openAI.ID, openRouter.ID}).Delete(&model.Credential{})
	})

	cred, err := pickSessionNameCredential(context.Background(), db, registry.Global())
	if err != nil {
		t.Fatalf("pick credential: %v", err)
	}
	if cred.ID != openRouter.ID {
		t.Fatalf("picked credential=%s want=%s", cred.ID, openRouter.ID)
	}
}

func seedSessionNameFixture(t *testing.T, db *gorm.DB, firstMessage string) model.Session {
	t.Helper()

	org := model.Org{Name: "session-name-org-" + uuid.NewString()[:8], Active: true}
	if err := db.Create(&org).Error; err != nil {
		t.Fatalf("create org: %v", err)
	}

	agent := model.Agent{
		OrgID:           &org.ID,
		Name:            "Agent-" + uuid.NewString()[:8],
		SandboxStrategy: "per_session",
		Model:           "deepseek-v4-flash",
		Tools:           model.JSON{},
		McpServers:      model.RawJSON("[]"),
		Skills:          model.JSON{},
		RuntimeConfig:   model.JSON{},
		Permissions:     model.JSON{},
		Resources:       model.JSON{},
		Status:          "active",
	}
	if err := db.Create(&agent).Error; err != nil {
		t.Fatalf("create agent: %v", err)
	}

	channel := model.Channel{
		OrgID:          org.ID,
		Name:           "engineering-" + uuid.NewString()[:8],
		Kind:           "standard",
		Visibility:     "public",
		DefaultAgentID: agent.ID,
		Origin:         "native",
	}
	if err := db.Create(&channel).Error; err != nil {
		t.Fatalf("create channel: %v", err)
	}

	session := model.Session{
		OrgID:             org.ID,
		ChannelID:         channel.ID,
		AgentID:           agent.ID,
		Model:             agent.Model,
		AccessMode:        "full",
		ReasoningEffort:   "high",
		Source:            "web",
		SourceResourceKey: uuid.NewString(),
		Name:              "investigate-linear-issue-placeholder",
		Status:            "active",
		AgentTurnStatus:   model.SessionAgentTurnIdle,
		IntegrationScopes: model.JSON{},
	}
	if err := db.Create(&session).Error; err != nil {
		t.Fatalf("create session: %v", err)
	}

	event := model.SessionEvent{
		OrgID:            org.ID,
		SessionID:        session.ID,
		AgentID:          agent.ID,
		RuntimeSessionID: session.ID.String(),
		EventID:          "user-" + uuid.NewString(),
		EventType:        "user.message",
		Source:           "web",
		SequenceNumber:   1,
		Payload:          model.JSON{"text": firstMessage},
		EventAt:          time.Now(),
	}
	if err := db.Create(&event).Error; err != nil {
		t.Fatalf("create session event: %v", err)
	}

	t.Cleanup(func() {
		db.Where("session_id = ?", session.ID).Delete(&model.SessionEvent{})
		db.Where("id = ?", session.ID).Delete(&model.Session{})
		db.Where("id = ?", channel.ID).Delete(&model.Channel{})
		db.Where("id = ?", agent.ID).Delete(&model.Agent{})
		db.Where("id = ?", org.ID).Delete(&model.Org{})
	})

	return session
}

func mustMarshalSessionNamePayload(t *testing.T, payload SessionNamePayload) []byte {
	t.Helper()

	raw, err := json.Marshal(payload)
	if err != nil {
		t.Fatalf("marshal payload: %v", err)
	}
	return raw
}
