package tasks

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/hibiken/asynq"
	"gorm.io/gorm"

	"github.com/usehivy/hivy/internal/cache"
	"github.com/usehivy/hivy/internal/credentials"
	"github.com/usehivy/hivy/internal/logging"
	"github.com/usehivy/hivy/internal/model"
	"github.com/usehivy/hivy/internal/registry"
	"github.com/usehivy/hivy/internal/trigger/hivy"
)

// messageContentMaxBytes caps the initial message content we send to the naming
// model. The naming prompt doesn't need the full webhook payload — the first
// couple KB almost always contain the signal.
const messageContentMaxBytes = 2048

// SessionNameHandler generates a durable auto-name for a session by calling
// the platform OpenRouter credential with gpt-4o-mini. It's idempotent:
// once session_name_auto_generated_at is set, the handler returns nil
// without making any external calls.
type SessionNameHandler struct {
	db                   *gorm.DB
	cacheManager         *cache.Manager
	reg                  *registry.Registry
	loadNamingCredential sessionNameCredentialLoader
	newCompletionClient  sessionNameClientFactory
}

// NewSessionNameHandler constructs a handler. Returns nil if the cache
// manager is nil — the handler requires credential decryption.
func NewSessionNameHandler(db *gorm.DB, cacheManager *cache.Manager) *SessionNameHandler {
	if db == nil || cacheManager == nil {
		return nil
	}
	return &SessionNameHandler{
		db:                   db,
		cacheManager:         cacheManager,
		reg:                  registry.Global(),
		loadNamingCredential: loadSessionNameCredential,
		newCompletionClient:  hivy.NewCompletionClient,
	}
}

// Handle runs one naming job. On retryable failures (provider timeouts,
// network) it returns an error so Asynq retries per MaxRetry. On permanent
// failures (missing credential, unsupported model) it returns nil so the
// job is dropped — the session simply keeps its placeholder name.
func (handler *SessionNameHandler) Handle(ctx context.Context, task *asynq.Task) error {
	var payload SessionNamePayload
	if err := json.Unmarshal(task.Payload(), &payload); err != nil {
		return fmt.Errorf("unmarshal payload: %w", err)
	}

	var session model.Session
	if err := handler.db.WithContext(ctx).
		Where("id = ?", payload.SessionID).
		First(&session).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return nil
		}
		return fmt.Errorf("load session: %w", err)
	}

	if session.SessionNameAutoGeneratedAt != nil {
		return nil
	}

	firstMessage, err := loadFirstMessageContent(ctx, handler.db, session.ID)
	if err != nil {
		return fmt.Errorf("load first message: %w", err)
	}
	if firstMessage == "" {
		return fmt.Errorf("first message not yet available")
	}

	loader := handler.loadNamingCredential
	if loader == nil {
		loader = loadSessionNameCredential
	}
	config, err := loader(ctx, handler.db, handler.cacheManager, handler.registry())
	if err != nil {
		if errors.Is(err, credentials.ErrNoSystemCredential) ||
			errors.Is(err, errSessionNameModelUnavailable) {
			logging.FromContext(ctx).WarnContext(ctx, "session auto-naming skipped",
				"session_id", session.ID,
				"error", err,
			)
			return nil
		}
		return fmt.Errorf("load naming credential: %w", err)
	}

	factory := handler.newCompletionClient
	if factory == nil {
		factory = hivy.NewCompletionClient
	}

	client := factory(config.credential, config.apiKey)
	name, err := generateSessionName(ctx, client, config.modelID, firstMessage)
	if err != nil {
		return fmt.Errorf("generate session name: %w", err)
	}
	name = normalizeGeneratedSessionName(name)
	if name == "" {
		return nil
	}

	now := time.Now()
	result := handler.db.WithContext(ctx).
		Model(&model.Session{}).
		Where("id = ? AND session_name_auto_generated_at IS NULL", session.ID).
		Updates(map[string]any{
			"name":                           name,
			"session_name_auto_generated_at": now,
		})
	if result.Error != nil {
		return fmt.Errorf("update session name: %w", result.Error)
	}

	logging.FromContext(ctx).InfoContext(ctx, "conversation named",
		"session_id", session.ID,
		"model", config.modelID,
		"name", name,
		"rows_updated", result.RowsAffected,
	)
	return nil
}

// loadFirstMessageContent returns the first user message content for a session, truncated.
func loadFirstMessageContent(ctx context.Context, db *gorm.DB, conversationID any) (string, error) {
	var event model.SessionEvent
	err := db.WithContext(ctx).
		Where("session_id = ? AND event_type IN ?", conversationID, []string{"message_received", "user.message.received", "user.message"}).
		Order("sequence_number ASC, event_at ASC").
		Limit(1).
		First(&event).Error
	if err != nil {
		if err == gorm.ErrRecordNotFound {
			return "", nil
		}
		return "", err
	}

	var data struct {
		Content string `json:"content"`
		Text    string `json:"text"`
	}
	data.Content, _ = event.Payload["content"].(string)
	data.Text, _ = event.Payload["text"].(string)
	content := strings.TrimSpace(data.Content)
	if content == "" {
		content = strings.TrimSpace(data.Text)
	}
	if len(content) > messageContentMaxBytes {
		content = content[:messageContentMaxBytes]
	}
	return content, nil
}
