apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - namespace.yaml
  - ../../config/env/staging
  - ../../apps/backend/base
  - ../../apps/nango/base
  - ../../apps/redis-exporter
  - ../../apps/data-backups
  - ../../apps/web/base
  - deployment-service-account.yaml
  - nango-postgres.yaml
  - nango-routes.yaml
  - postgres.yaml
  - redis.yaml
  - resources.yaml
  - network-policies.yaml
  - routes.yaml
  - web-routes.yaml
patches:
  - path: api-patch.yaml
  - path: qdrant-backup-patch.yaml
  - path: redis-backup-patch.yaml
  - path: worker-patch.yaml
  - path: web-patch.yaml
images:
  - name: ghcr.io/usehivy/hivy
    newName: ghcr.io/usehivy/hivy
    digest: sha256:59071935749eebb9b79634e96b7f880e29e0b75e5d799bab1c25e4623bed880c
  - name: ghcr.io/usehivy/integrations
    newName: ghcr.io/usehivy/integrations
    digest: sha256:75a2e6e31b1d1ec3e798e334c84ec5aff776c23c30a50847a19f7abde1f17334
  - name: ghcr.io/usehivy/web
    newName: ghcr.io/usehivy/web
    digest: sha256:fdef9f5a488e4465a24e93d21f3e6b8a7fd2532b3527c816ae1cb97f5eb7f903
labels:
  - pairs:
      app.kubernetes.io/part-of: hivy
      hivy.io/environment: staging
