apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    hivy.io/environment: staging
    hivy.io/apply-phase: foundation
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
