apiVersion: batch/v1
kind: CronJob
metadata:
  name: qdrant-backup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: snapshot
              env:
                - name: QDRANT_PEERS
                  value: "1"
