apiVersion: batch/v1
kind: CronJob
metadata:
  name: backend-redis-backup
spec:
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: backup-and-validate
              env:
                - name: REDIS_BACKUP_MODE
                  value: standalone
          containers:
            - name: upload
              env:
                - name: REDIS_BACKUP_MODE
                  value: standalone
