apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-api-http-redirect
  labels:
    app.kubernetes.io/name: hivy-backend
    hivy.io/apply-phase: workload
spec:
  parentRefs:
    - name: public
      namespace: ingress-public
      sectionName: http
  hostnames:
    - staging.api.usehivy.com
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-api
  labels:
    app.kubernetes.io/name: hivy-backend
    hivy.io/apply-phase: workload
spec:
  parentRefs:
    - name: public
      namespace: ingress-public
      sectionName: https
    - name: public
      namespace: ingress-public
      sectionName: private-https
  hostnames:
    - staging.api.usehivy.com
  rules:
    - backendRefs:
        - name: backend-api
          port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-mcp
  labels:
    hivy.io/apply-phase: workload
spec:
  parentRefs:
    - name: public
      namespace: ingress-public
      sectionName: https
    - name: public
      namespace: ingress-public
      sectionName: private-https
  hostnames:
    - staging.mcp.usehivy.com
  rules:
    - backendRefs:
        - name: backend-api
          port: 8081
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-proxy
  labels:
    hivy.io/apply-phase: workload
spec:
  parentRefs:
    - name: public
      namespace: ingress-public
      sectionName: https
    - name: public
      namespace: ingress-public
      sectionName: private-https
  hostnames:
    - staging.proxy.usehivy.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /v1/proxy/
      backendRefs:
        - name: backend-api
          port: 8080
