apiVersion: v1
kind: Service
metadata:
  name: nango
  labels:
    app.kubernetes.io/name: nango
    app.kubernetes.io/component: connections
    hivy.io/apply-phase: workload
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nango
    app.kubernetes.io/component: connections
  ports:
    - name: http
      port: 3003
      targetPort: http
      protocol: TCP
